// Copyright 2009-2012 Mars Saxman.
//
// Radian is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 2 of the License, or (at your option) any later
// version.
//
// Radian is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// Radian.  If not, see <http://www.gnu.org/licenses/>.


#include <vector>
#include <assert.h>
#include "charclasses.h"

// Unless otherwise specified, all character data in this file comes from
// Unicode 5.0:
// <http://www.unicode.org/Public/5.0.0/ucd/PropList.txt>

struct PropRange
{
    uchar_t begin;
    uchar_t end;
};
// We will keep one PropTable for each character class we are interested in.
// The PropTable provides constant-time lookup for characters in the BMP.
// Characters outside the BMP will still work, but we do not expect to
// encounter them very often, so we expect that O(log n) lookup will suffice.
class PropTable
{
    public:
        PropTable( PropRange *srcmap );
        bool Lookup( uchar_t ch );
    protected:
        void bitset( unsigned int index );
        bool bitget( unsigned int index );
        PropRange *mSrcMap;
        unsigned int mSrcMapSize;
        unsigned char table[8192];
};

PropTable::PropTable( PropRange *srcmap ):
    mSrcMap(srcmap),
    mSrcMapSize(0)
{
    // Zero the BMP flag table.
    for (unsigned int index = 0; index < 8192; index++) {
        table[0] = 0;
    }
    // Iterate through the source data. Store 
    while (mSrcMap[mSrcMapSize].begin) {
        PropRange *mapEntry = &mSrcMap[mSrcMapSize];
        assert( mapEntry->begin <= mapEntry->end );
        for (uchar_t ch = mapEntry->begin; ch <= mapEntry->end; ch++) {
            if (ch <= 0xFFFF) {
                bitset( ch );
            }
        }
        mSrcMapSize++;
    }
}

bool PropTable::Lookup( uchar_t ch )
{
    if (ch <= 0xFFFF) {
        // char is in the BMP, so we should have a bitvector value for it
        return bitget( ch );
    } else {
        // char is outside the BMP, so we will do a binary search on the source
        unsigned int low = 0;
        unsigned int high = mSrcMapSize - 1;
        while (low <= high) {
            unsigned int middle = (low + high) / 2;
            PropRange *mapEntry = &mSrcMap[middle];
            if (ch < mapEntry->begin) {
                high = middle - 1;
            } else if (ch > mapEntry->end) {
                low = middle + 1;
            } else {
                return true;
            }
        }
        return false;
    }
}

void PropTable::bitset( unsigned int ch )
{
    unsigned int index = ch >> 3;
    assert( index < 8192 );
    table[index] |= (1 << (ch % 8));
}

bool PropTable::bitget( unsigned int ch )
{
    unsigned int index = ch >> 3;
    assert( index < 8192 );
    return (table[index] & (1 << (ch % 8))) != 0;
}

bool Unicode::Pattern_White_Space( uchar_t ch )
{
    PropRange srcmap[] = {
        {0x0009, 0x000D},    // CHARACTER TABULATION (HT) - CARRIAGE RETURN (CR)
        {0x0020, 0x0020},    // SPACE
        {0x0085, 0x0085},    // NEXT LINE (NEL)
        {0x00A0, 0x00A0},    // NO-BREAK SPACE
        {0x1680, 0x1680},    // OGHAM SPACE MARK
        {0x180E, 0x180E},    // MONGOLIAN VOWEL SEPARATOR
        {0x2000, 0x200A},    // EN QUAD - HAIR SPACE
        {0x2028, 0x2029},    // LINE SEPARATOR - PARAGRAPH SEPARATOR
        {0x202F, 0x202F},    // NARROW NO-BREAK SPACE
        {0x205F, 0x205F},    // MEDIUM MATHEMATICAL SPACE
        {0x3000, 0x3000},    // IDEOGRAPHIC SPACE
        {0, 0},    // list terminator
  };
    static PropTable pattern( srcmap );
    return pattern.Lookup( ch );
}

bool Unicode::XID_Start( uchar_t ch )
{
    PropRange srcmap[] = {
        {0x0041, 0x005A},        // LATIN CAPITAL LETTER A..LATIN CAPITAL LETTER Z
        {0x0061, 0x007A},        // LATIN SMALL LETTER A..LATIN SMALL LETTER Z
        {0x00AA, 0x00AA},        // FEMININE ORDINAL INDICATOR
        {0x00B5, 0x00B5},        // MICRO SIGN
        {0x00BA, 0x00BA},        // MASCULINE ORDINAL INDICATOR
        {0x00C0, 0x00D6},        // LATIN CAPITAL LETTER A WITH GRAVE..LATIN CAPITAL LETTER O WITH DIAERESIS
        {0x00D8, 0x00F6},        // LATIN CAPITAL LETTER O WITH STROKE..LATIN SMALL LETTER O WITH DIAERESIS
        {0x00F8, 0x01BA},        // LATIN SMALL LETTER O WITH STROKE..LATIN SMALL LETTER EZH WITH TAIL
        {0x01BB, 0x01BB},        // LATIN LETTER TWO WITH STROKE
        {0x01BC, 0x01BF},        // LATIN CAPITAL LETTER TONE FIVE..LATIN LETTER WYNN
        {0x01C0, 0x01C3},        // LATIN LETTER DENTAL CLICK..LATIN LETTER RETROFLEX CLICK
        {0x01C4, 0x0293},        // LATIN CAPITAL LETTER DZ WITH CARON..LATIN SMALL LETTER EZH WITH CURL
        {0x0294, 0x0294},        // LATIN LETTER GLOTTAL STOP
        {0x0295, 0x02AF},        // LATIN LETTER PHARYNGEAL VOICED FRICATIVE..LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL
        {0x02B0, 0x02C1},        // MODIFIER LETTER SMALL H..MODIFIER LETTER REVERSED GLOTTAL STOP
        {0x02C6, 0x02D1},        // MODIFIER LETTER CIRCUMFLEX ACCENT..MODIFIER LETTER HALF TRIANGULAR COLON
        {0x02E0, 0x02E4},        // MODIFIER LETTER SMALL GAMMA..MODIFIER LETTER SMALL REVERSED GLOTTAL STOP
        {0x02EE, 0x02EE},        // MODIFIER LETTER DOUBLE APOSTROPHE
        {0x037B, 0x037D},        // GREEK SMALL REVERSED LUNATE SIGMA SYMBOL..GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
        {0x0386, 0x0386},        // GREEK CAPITAL LETTER ALPHA WITH TONOS
        {0x0388, 0x038A},        // GREEK CAPITAL LETTER EPSILON WITH TONOS..GREEK CAPITAL LETTER IOTA WITH TONOS
        {0x038C, 0x038C},        // GREEK CAPITAL LETTER OMICRON WITH TONOS
        {0x038E, 0x03A1},        // GREEK CAPITAL LETTER UPSILON WITH TONOS..GREEK CAPITAL LETTER RHO
        {0x03A3, 0x03CE},        // GREEK CAPITAL LETTER SIGMA..GREEK SMALL LETTER OMEGA WITH TONOS
        {0x03D0, 0x03F5},        // GREEK BETA SYMBOL..GREEK LUNATE EPSILON SYMBOL
        {0x03F7, 0x0481},        // GREEK CAPITAL LETTER SHO..CYRILLIC SMALL LETTER KOPPA
        {0x048A, 0x0513},        // CYRILLIC CAPITAL LETTER SHORT I WITH TAIL..CYRILLIC SMALL LETTER EL WITH HOOK
        {0x0531, 0x0556},        // ARMENIAN CAPITAL LETTER AYB..ARMENIAN CAPITAL LETTER FEH
        {0x0559, 0x0559},        // ARMENIAN MODIFIER LETTER LEFT HALF RING
        {0x0561, 0x0587},        // ARMENIAN SMALL LETTER AYB..ARMENIAN SMALL LIGATURE ECH YIWN
        {0x05D0, 0x05EA},        // HEBREW LETTER ALEF..HEBREW LETTER TAV
        {0x05F0, 0x05F2},        // HEBREW LIGATURE YIDDISH DOUBLE VAV..HEBREW LIGATURE YIDDISH DOUBLE YOD
        {0x0621, 0x063A},        // ARABIC LETTER HAMZA..ARABIC LETTER GHAIN
        {0x0640, 0x0640},        // ARABIC TATWEEL
        {0x0641, 0x064A},        // ARABIC LETTER FEH..ARABIC LETTER YEH
        {0x066E, 0x066F},        // ARABIC LETTER DOTLESS BEH..ARABIC LETTER DOTLESS QAF
        {0x0671, 0x06D3},        // ARABIC LETTER ALEF WASLA..ARABIC LETTER YEH BARREE WITH HAMZA ABOVE
        {0x06D5, 0x06D5},        // ARABIC LETTER AE
        {0x06E5, 0x06E6},        // ARABIC SMALL WAW..ARABIC SMALL YEH
        {0x06EE, 0x06EF},        // ARABIC LETTER DAL WITH INVERTED V..ARABIC LETTER REH WITH INVERTED V
        {0x06FA, 0x06FC},        // ARABIC LETTER SHEEN WITH DOT BELOW..ARABIC LETTER GHAIN WITH DOT BELOW
        {0x06FF, 0x06FF},        // ARABIC LETTER HEH WITH INVERTED V
        {0x0710, 0x0710},        // SYRIAC LETTER ALAPH
        {0x0712, 0x072F},        // SYRIAC LETTER BETH..SYRIAC LETTER PERSIAN DHALATH
        {0x074D, 0x076D},        // SYRIAC LETTER SOGDIAN ZHAIN..ARABIC LETTER SEEN WITH TWO DOTS VERTICALLY ABOVE
        {0x0780, 0x07A5},        // THAANA LETTER HAA..THAANA LETTER WAAVU
        {0x07B1, 0x07B1},        // THAANA LETTER NAA
        {0x07CA, 0x07EA},        // NKO LETTER A..NKO LETTER JONA RA
        {0x07F4, 0x07F5},        // NKO HIGH TONE APOSTROPHE..NKO LOW TONE APOSTROPHE
        {0x07FA, 0x07FA},        // NKO LAJANYALAN
        {0x0904, 0x0939},        // DEVANAGARI LETTER SHORT A..DEVANAGARI LETTER HA
        {0x093D, 0x093D},        // DEVANAGARI SIGN AVAGRAHA
        {0x0950, 0x0950},        // DEVANAGARI OM
        {0x0958, 0x0961},        // DEVANAGARI LETTER QA..DEVANAGARI LETTER VOCALIC LL
        {0x097B, 0x097F},        // DEVANAGARI LETTER GGA..DEVANAGARI LETTER BBA
        {0x0985, 0x098C},        // BENGALI LETTER A..BENGALI LETTER VOCALIC L
        {0x098F, 0x0990},        // BENGALI LETTER E..BENGALI LETTER AI
        {0x0993, 0x09A8},        // BENGALI LETTER O..BENGALI LETTER NA
        {0x09AA, 0x09B0},        // BENGALI LETTER PA..BENGALI LETTER RA
        {0x09B2, 0x09B2},        // BENGALI LETTER LA
        {0x09B6, 0x09B9},        // BENGALI LETTER SHA..BENGALI LETTER HA
        {0x09BD, 0x09BD},        // BENGALI SIGN AVAGRAHA
        {0x09CE, 0x09CE},        // BENGALI LETTER KHANDA TA
        {0x09DC, 0x09DD},        // BENGALI LETTER RRA..BENGALI LETTER RHA
        {0x09DF, 0x09E1},        // BENGALI LETTER YYA..BENGALI LETTER VOCALIC LL
        {0x09F0, 0x09F1},        // BENGALI LETTER RA WITH MIDDLE DIAGONAL..BENGALI LETTER RA WITH LOWER DIAGONAL
        {0x0A05, 0x0A0A},        // GURMUKHI LETTER A..GURMUKHI LETTER UU
        {0x0A0F, 0x0A10},        // GURMUKHI LETTER EE..GURMUKHI LETTER AI
        {0x0A13, 0x0A28},        // GURMUKHI LETTER OO..GURMUKHI LETTER NA
        {0x0A2A, 0x0A30},        // GURMUKHI LETTER PA..GURMUKHI LETTER RA
        {0x0A32, 0x0A33},        // GURMUKHI LETTER LA..GURMUKHI LETTER LLA
        {0x0A35, 0x0A36},        // GURMUKHI LETTER VA..GURMUKHI LETTER SHA
        {0x0A38, 0x0A39},        // GURMUKHI LETTER SA..GURMUKHI LETTER HA
        {0x0A59, 0x0A5C},        // GURMUKHI LETTER KHHA..GURMUKHI LETTER RRA
        {0x0A5E, 0x0A5E},        // GURMUKHI LETTER FA
        {0x0A72, 0x0A74},        // GURMUKHI IRI..GURMUKHI EK ONKAR
        {0x0A85, 0x0A8D},        // GUJARATI LETTER A..GUJARATI VOWEL CANDRA E
        {0x0A8F, 0x0A91},        // GUJARATI LETTER E..GUJARATI VOWEL CANDRA O
        {0x0A93, 0x0AA8},        // GUJARATI LETTER O..GUJARATI LETTER NA
        {0x0AAA, 0x0AB0},        // GUJARATI LETTER PA..GUJARATI LETTER RA
        {0x0AB2, 0x0AB3},        // GUJARATI LETTER LA..GUJARATI LETTER LLA
        {0x0AB5, 0x0AB9},        // GUJARATI LETTER VA..GUJARATI LETTER HA
        {0x0ABD, 0x0ABD},        // GUJARATI SIGN AVAGRAHA
        {0x0AD0, 0x0AD0},        // GUJARATI OM
        {0x0AE0, 0x0AE1},        // GUJARATI LETTER VOCALIC RR..GUJARATI LETTER VOCALIC LL
        {0x0B05, 0x0B0C},        // ORIYA LETTER A..ORIYA LETTER VOCALIC L
        {0x0B0F, 0x0B10},        // ORIYA LETTER E..ORIYA LETTER AI
        {0x0B13, 0x0B28},        // ORIYA LETTER O..ORIYA LETTER NA
        {0x0B2A, 0x0B30},        // ORIYA LETTER PA..ORIYA LETTER RA
        {0x0B32, 0x0B33},        // ORIYA LETTER LA..ORIYA LETTER LLA
        {0x0B35, 0x0B39},        // ORIYA LETTER VA..ORIYA LETTER HA
        {0x0B3D, 0x0B3D},        // ORIYA SIGN AVAGRAHA
        {0x0B5C, 0x0B5D},        // ORIYA LETTER RRA..ORIYA LETTER RHA
        {0x0B5F, 0x0B61},        // ORIYA LETTER YYA..ORIYA LETTER VOCALIC LL
        {0x0B71, 0x0B71},        // ORIYA LETTER WA
        {0x0B83, 0x0B83},        // TAMIL SIGN VISARGA
        {0x0B85, 0x0B8A},        // TAMIL LETTER A..TAMIL LETTER UU
        {0x0B8E, 0x0B90},        // TAMIL LETTER E..TAMIL LETTER AI
        {0x0B92, 0x0B95},        // TAMIL LETTER O..TAMIL LETTER KA
        {0x0B99, 0x0B9A},        // TAMIL LETTER NGA..TAMIL LETTER CA
        {0x0B9C, 0x0B9C},        // TAMIL LETTER JA
        {0x0B9E, 0x0B9F},        // TAMIL LETTER NYA..TAMIL LETTER TTA
        {0x0BA3, 0x0BA4},        // TAMIL LETTER NNA..TAMIL LETTER TA
        {0x0BA8, 0x0BAA},        // TAMIL LETTER NA..TAMIL LETTER PA
        {0x0BAE, 0x0BB9},        // TAMIL LETTER MA..TAMIL LETTER HA
        {0x0C05, 0x0C0C},        // TELUGU LETTER A..TELUGU LETTER VOCALIC L
        {0x0C0E, 0x0C10},        // TELUGU LETTER E..TELUGU LETTER AI
        {0x0C12, 0x0C28},        // TELUGU LETTER O..TELUGU LETTER NA
        {0x0C2A, 0x0C33},        // TELUGU LETTER PA..TELUGU LETTER LLA
        {0x0C35, 0x0C39},        // TELUGU LETTER VA..TELUGU LETTER HA
        {0x0C60, 0x0C61},        // TELUGU LETTER VOCALIC RR..TELUGU LETTER VOCALIC LL
        {0x0C85, 0x0C8C},        // KANNADA LETTER A..KANNADA LETTER VOCALIC L
        {0x0C8E, 0x0C90},        // KANNADA LETTER E..KANNADA LETTER AI
        {0x0C92, 0x0CA8},        // KANNADA LETTER O..KANNADA LETTER NA
        {0x0CAA, 0x0CB3},        // KANNADA LETTER PA..KANNADA LETTER LLA
        {0x0CB5, 0x0CB9},        // KANNADA LETTER VA..KANNADA LETTER HA
        {0x0CBD, 0x0CBD},        // KANNADA SIGN AVAGRAHA
        {0x0CDE, 0x0CDE},        // KANNADA LETTER FA
        {0x0CE0, 0x0CE1},        // KANNADA LETTER VOCALIC RR..KANNADA LETTER VOCALIC LL
        {0x0D05, 0x0D0C},        // MALAYALAM LETTER A..MALAYALAM LETTER VOCALIC L
        {0x0D0E, 0x0D10},        // MALAYALAM LETTER E..MALAYALAM LETTER AI
        {0x0D12, 0x0D28},        // MALAYALAM LETTER O..MALAYALAM LETTER NA
        {0x0D2A, 0x0D39},        // MALAYALAM LETTER PA..MALAYALAM LETTER HA
        {0x0D60, 0x0D61},        // MALAYALAM LETTER VOCALIC RR..MALAYALAM LETTER VOCALIC LL
        {0x0D85, 0x0D96},        // SINHALA LETTER AYANNA..SINHALA LETTER AUYANNA
        {0x0D9A, 0x0DB1},        // SINHALA LETTER ALPAPRAANA KAYANNA..SINHALA LETTER DANTAJA NAYANNA
        {0x0DB3, 0x0DBB},        // SINHALA LETTER SANYAKA DAYANNA..SINHALA LETTER RAYANNA
        {0x0DBD, 0x0DBD},        // SINHALA LETTER DANTAJA LAYANNA
        {0x0DC0, 0x0DC6},        // SINHALA LETTER VAYANNA..SINHALA LETTER FAYANNA
        {0x0E01, 0x0E30},        // THAI CHARACTER KO KAI..THAI CHARACTER SARA A
        {0x0E32, 0x0E32},        // THAI CHARACTER SARA AA
        {0x0E40, 0x0E45},        // THAI CHARACTER SARA E..THAI CHARACTER LAKKHANGYAO
        {0x0E46, 0x0E46},        // THAI CHARACTER MAIYAMOK
        {0x0E81, 0x0E82},        // LAO LETTER KO..LAO LETTER KHO SUNG
        {0x0E84, 0x0E84},        // LAO LETTER KHO TAM
        {0x0E87, 0x0E88},        // LAO LETTER NGO..LAO LETTER CO
        {0x0E8A, 0x0E8A},        // LAO LETTER SO TAM
        {0x0E8D, 0x0E8D},        // LAO LETTER NYO
        {0x0E94, 0x0E97},        // LAO LETTER DO..LAO LETTER THO TAM
        {0x0E99, 0x0E9F},        // LAO LETTER NO..LAO LETTER FO SUNG
        {0x0EA1, 0x0EA3},        // LAO LETTER MO..LAO LETTER LO LING
        {0x0EA5, 0x0EA5},        // LAO LETTER LO LOOT
        {0x0EA7, 0x0EA7},        // LAO LETTER WO
        {0x0EAA, 0x0EAB},        // LAO LETTER SO SUNG..LAO LETTER HO SUNG
        {0x0EAD, 0x0EB0},        // LAO LETTER O..LAO VOWEL SIGN A
        {0x0EB2, 0x0EB2},        // LAO VOWEL SIGN AA
        {0x0EBD, 0x0EBD},        // LAO SEMIVOWEL SIGN NYO
        {0x0EC0, 0x0EC4},        // LAO VOWEL SIGN E..LAO VOWEL SIGN AI
        {0x0EC6, 0x0EC6},        // LAO KO LA
        {0x0EDC, 0x0EDD},        // LAO HO NO..LAO HO MO
        {0x0F00, 0x0F00},        // TIBETAN SYLLABLE OM
        {0x0F40, 0x0F47},        // TIBETAN LETTER KA..TIBETAN LETTER JA
        {0x0F49, 0x0F6A},        // TIBETAN LETTER NYA..TIBETAN LETTER FIXED-FORM RA
        {0x0F88, 0x0F8B},        // TIBETAN SIGN LCE TSA CAN..TIBETAN SIGN GRU MED RGYINGS
        {0x1000, 0x1021},        // MYANMAR LETTER KA..MYANMAR LETTER A
        {0x1023, 0x1027},        // MYANMAR LETTER I..MYANMAR LETTER E
        {0x1029, 0x102A},        // MYANMAR LETTER O..MYANMAR LETTER AU
        {0x1050, 0x1055},        // MYANMAR LETTER SHA..MYANMAR LETTER VOCALIC LL
        {0x10A0, 0x10C5},        // GEORGIAN CAPITAL LETTER AN..GEORGIAN CAPITAL LETTER HOE
        {0x10D0, 0x10FA},        // GEORGIAN LETTER AN..GEORGIAN LETTER AIN
        {0x10FC, 0x10FC},        // MODIFIER LETTER GEORGIAN NAR
        {0x1100, 0x1159},        // HANGUL CHOSEONG KIYEOK..HANGUL CHOSEONG YEORINHIEUH
        {0x115F, 0x11A2},        // HANGUL CHOSEONG FILLER..HANGUL JUNGSEONG SSANGARAEA
        {0x11A8, 0x11F9},        // HANGUL JONGSEONG KIYEOK..HANGUL JONGSEONG YEORINHIEUH
        {0x1200, 0x1248},        // ETHIOPIC SYLLABLE HA..ETHIOPIC SYLLABLE QWA
        {0x124A, 0x124D},        // ETHIOPIC SYLLABLE QWI..ETHIOPIC SYLLABLE QWE
        {0x1250, 0x1256},        // ETHIOPIC SYLLABLE QHA..ETHIOPIC SYLLABLE QHO
        {0x1258, 0x1258},        // ETHIOPIC SYLLABLE QHWA
        {0x125A, 0x125D},        // ETHIOPIC SYLLABLE QHWI..ETHIOPIC SYLLABLE QHWE
        {0x1260, 0x1288},        // ETHIOPIC SYLLABLE BA..ETHIOPIC SYLLABLE XWA
        {0x128A, 0x128D},        // ETHIOPIC SYLLABLE XWI..ETHIOPIC SYLLABLE XWE
        {0x1290, 0x12B0},        // ETHIOPIC SYLLABLE NA..ETHIOPIC SYLLABLE KWA
        {0x12B2, 0x12B5},        // ETHIOPIC SYLLABLE KWI..ETHIOPIC SYLLABLE KWE
        {0x12B8, 0x12BE},        // ETHIOPIC SYLLABLE KXA..ETHIOPIC SYLLABLE KXO
        {0x12C0, 0x12C0},        // ETHIOPIC SYLLABLE KXWA
        {0x12C2, 0x12C5},        // ETHIOPIC SYLLABLE KXWI..ETHIOPIC SYLLABLE KXWE
        {0x12C8, 0x12D6},        // ETHIOPIC SYLLABLE WA..ETHIOPIC SYLLABLE PHARYNGEAL O
        {0x12D8, 0x1310},        // ETHIOPIC SYLLABLE ZA..ETHIOPIC SYLLABLE GWA
        {0x1312, 0x1315},        // ETHIOPIC SYLLABLE GWI..ETHIOPIC SYLLABLE GWE
        {0x1318, 0x135A},        // ETHIOPIC SYLLABLE GGA..ETHIOPIC SYLLABLE FYA
        {0x1380, 0x138F},        // ETHIOPIC SYLLABLE SEBATBEIT MWA..ETHIOPIC SYLLABLE PWE
        {0x13A0, 0x13F4},        // CHEROKEE LETTER A..CHEROKEE LETTER YV
        {0x1401, 0x166C},        // CANADIAN SYLLABICS E..CANADIAN SYLLABICS CARRIER TTSA
        {0x166F, 0x1676},        // CANADIAN SYLLABICS QAI..CANADIAN SYLLABICS NNGAA
        {0x1681, 0x169A},        // OGHAM LETTER BEITH..OGHAM LETTER PEITH
        {0x16A0, 0x16EA},        // RUNIC LETTER FEHU FEOH FE F..RUNIC LETTER X
        {0x16EE, 0x16F0},        // RUNIC ARLAUG SYMBOL..RUNIC BELGTHOR SYMBOL
        {0x1700, 0x170C},        // TAGALOG LETTER A..TAGALOG LETTER YA
        {0x170E, 0x1711},        // TAGALOG LETTER LA..TAGALOG LETTER HA
        {0x1720, 0x1731},        // HANUNOO LETTER A..HANUNOO LETTER HA
        {0x1740, 0x1751},        // BUHID LETTER A..BUHID LETTER HA
        {0x1760, 0x176C},        // TAGBANWA LETTER A..TAGBANWA LETTER YA
        {0x176E, 0x1770},        // TAGBANWA LETTER LA..TAGBANWA LETTER SA
        {0x1780, 0x17B3},        // KHMER LETTER KA..KHMER INDEPENDENT VOWEL QAU
        {0x17D7, 0x17D7},        // KHMER SIGN LEK TOO
        {0x17DC, 0x17DC},        // KHMER SIGN AVAKRAHASANYA
        {0x1820, 0x1842},        // MONGOLIAN LETTER A..MONGOLIAN LETTER CHI
        {0x1843, 0x1843},        // MONGOLIAN LETTER TODO LONG VOWEL SIGN
        {0x1844, 0x1877},        // MONGOLIAN LETTER TODO E..MONGOLIAN LETTER MANCHU ZHA
        {0x1880, 0x18A8},        // MONGOLIAN LETTER ALI GALI ANUSVARA ONE..MONGOLIAN LETTER MANCHU ALI GALI BHA
        {0x1900, 0x191C},        // LIMBU VOWEL-CARRIER LETTER..LIMBU LETTER HA
        {0x1950, 0x196D},        // TAI LE LETTER KA..TAI LE LETTER AI
        {0x1970, 0x1974},        // TAI LE LETTER TONE-2..TAI LE LETTER TONE-6
        {0x1980, 0x19A9},        // NEW TAI LUE LETTER HIGH QA..NEW TAI LUE LETTER LOW XVA
        {0x19C1, 0x19C7},        // NEW TAI LUE LETTER FINAL V..NEW TAI LUE LETTER FINAL B
        {0x1A00, 0x1A16},        // BUGINESE LETTER KA..BUGINESE LETTER HA
        {0x1B05, 0x1B33},        // BALINESE LETTER AKARA..BALINESE LETTER HA
        {0x1B45, 0x1B4B},        // BALINESE LETTER KAF SASAK..BALINESE LETTER ASYURA SASAK
        {0x1D00, 0x1D2B},        // LATIN LETTER SMALL CAPITAL A..CYRILLIC LETTER SMALL CAPITAL EL
        {0x1D2C, 0x1D61},        // MODIFIER LETTER CAPITAL A..MODIFIER LETTER SMALL CHI
        {0x1D62, 0x1D77},        // LATIN SUBSCRIPT SMALL LETTER I..LATIN SMALL LETTER TURNED G
        {0x1D78, 0x1D78},        // MODIFIER LETTER CYRILLIC EN
        {0x1D79, 0x1D9A},        // LATIN SMALL LETTER INSULAR G..LATIN SMALL LETTER EZH WITH RETROFLEX HOOK
        {0x1D9B, 0x1DBF},        // MODIFIER LETTER SMALL TURNED ALPHA..MODIFIER LETTER SMALL THETA
        {0x1E00, 0x1E9B},        // LATIN CAPITAL LETTER A WITH RING BELOW..LATIN SMALL LETTER LONG S WITH DOT ABOVE
        {0x1EA0, 0x1EF9},        // LATIN CAPITAL LETTER A WITH DOT BELOW..LATIN SMALL LETTER Y WITH TILDE
        {0x1F00, 0x1F15},        // GREEK SMALL LETTER ALPHA WITH PSILI..GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
        {0x1F18, 0x1F1D},        // GREEK CAPITAL LETTER EPSILON WITH PSILI..GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
        {0x1F20, 0x1F45},        // GREEK SMALL LETTER ETA WITH PSILI..GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
        {0x1F48, 0x1F4D},        // GREEK CAPITAL LETTER OMICRON WITH PSILI..GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
        {0x1F50, 0x1F57},        // GREEK SMALL LETTER UPSILON WITH PSILI..GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
        {0x1F59, 0x1F59},        // GREEK CAPITAL LETTER UPSILON WITH DASIA
        {0x1F5B, 0x1F5B},        // GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
        {0x1F5D, 0x1F5D},        // GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
        {0x1F5F, 0x1F7D},        // GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI..GREEK SMALL LETTER OMEGA WITH OXIA
        {0x1F80, 0x1FB4},        // GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI..GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
        {0x1FB6, 0x1FBC},        // GREEK SMALL LETTER ALPHA WITH PERISPOMENI..GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
        {0x1FBE, 0x1FBE},        // GREEK PROSGEGRAMMENI
        {0x1FC2, 0x1FC4},        // GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI..GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
        {0x1FC6, 0x1FCC},        // GREEK SMALL LETTER ETA WITH PERISPOMENI..GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
        {0x1FD0, 0x1FD3},        // GREEK SMALL LETTER IOTA WITH VRACHY..GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
        {0x1FD6, 0x1FDB},        // GREEK SMALL LETTER IOTA WITH PERISPOMENI..GREEK CAPITAL LETTER IOTA WITH OXIA
        {0x1FE0, 0x1FEC},        // GREEK SMALL LETTER UPSILON WITH VRACHY..GREEK CAPITAL LETTER RHO WITH DASIA
        {0x1FF2, 0x1FF4},        // GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI..GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
        {0x1FF6, 0x1FFC},        // GREEK SMALL LETTER OMEGA WITH PERISPOMENI..GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
        {0x2071, 0x2071},        // SUPERSCRIPT LATIN SMALL LETTER I
        {0x207F, 0x207F},        // SUPERSCRIPT LATIN SMALL LETTER N
        {0x2090, 0x2094},        // LATIN SUBSCRIPT SMALL LETTER A..LATIN SUBSCRIPT SMALL LETTER SCHWA
        {0x2102, 0x2102},        // DOUBLE-STRUCK CAPITAL C
        {0x2107, 0x2107},        // EULER CONSTANT
        {0x210A, 0x2113},        // SCRIPT SMALL G..SCRIPT SMALL L
        {0x2115, 0x2115},        // DOUBLE-STRUCK CAPITAL N
        {0x2118, 0x2118},        // SCRIPT CAPITAL P
        {0x2119, 0x211D},        // DOUBLE-STRUCK CAPITAL P..DOUBLE-STRUCK CAPITAL R
        {0x2124, 0x2124},        // DOUBLE-STRUCK CAPITAL Z
        {0x2126, 0x2126},        // OHM SIGN
        {0x2128, 0x2128},        // BLACK-LETTER CAPITAL Z
        {0x212A, 0x212D},        // KELVIN SIGN..BLACK-LETTER CAPITAL C
        {0x212E, 0x212E},        // ESTIMATED SYMBOL
        {0x212F, 0x2134},        // SCRIPT SMALL E..SCRIPT SMALL O
        {0x2135, 0x2138},        // ALEF SYMBOL..DALET SYMBOL
        {0x2139, 0x2139},        // INFORMATION SOURCE
        {0x213C, 0x213F},        // DOUBLE-STRUCK SMALL PI..DOUBLE-STRUCK CAPITAL PI
        {0x2145, 0x2149},        // DOUBLE-STRUCK ITALIC CAPITAL D..DOUBLE-STRUCK ITALIC SMALL J
        {0x214E, 0x214E},        // TURNED SMALL F
        {0x2160, 0x2182},        // ROMAN NUMERAL ONE..ROMAN NUMERAL TEN THOUSAND
        {0x2183, 0x2184},        // ROMAN NUMERAL REVERSED ONE HUNDRED..LATIN SMALL LETTER REVERSED C
        {0x2C00, 0x2C2E},        // GLAGOLITIC CAPITAL LETTER AZU..GLAGOLITIC CAPITAL LETTER LATINATE MYSLITE
        {0x2C30, 0x2C5E},        // GLAGOLITIC SMALL LETTER AZU..GLAGOLITIC SMALL LETTER LATINATE MYSLITE
        {0x2C60, 0x2C6C},        // LATIN CAPITAL LETTER L WITH DOUBLE BAR..LATIN SMALL LETTER Z WITH DESCENDER
        {0x2C74, 0x2C77},        // LATIN SMALL LETTER V WITH CURL..LATIN SMALL LETTER TAILLESS PHI
        {0x2C80, 0x2CE4},        // COPTIC CAPITAL LETTER ALFA..COPTIC SYMBOL KAI
        {0x2D00, 0x2D25},        // GEORGIAN SMALL LETTER AN..GEORGIAN SMALL LETTER HOE
        {0x2D30, 0x2D65},        // TIFINAGH LETTER YA..TIFINAGH LETTER YAZZ
        {0x2D6F, 0x2D6F},        // TIFINAGH MODIFIER LETTER LABIALIZATION MARK
        {0x2D80, 0x2D96},        // ETHIOPIC SYLLABLE LOA..ETHIOPIC SYLLABLE GGWE
        {0x2DA0, 0x2DA6},        // ETHIOPIC SYLLABLE SSA..ETHIOPIC SYLLABLE SSO
        {0x2DA8, 0x2DAE},        // ETHIOPIC SYLLABLE CCA..ETHIOPIC SYLLABLE CCO
        {0x2DB0, 0x2DB6},        // ETHIOPIC SYLLABLE ZZA..ETHIOPIC SYLLABLE ZZO
        {0x2DB8, 0x2DBE},        // ETHIOPIC SYLLABLE CCHA..ETHIOPIC SYLLABLE CCHO
        {0x2DC0, 0x2DC6},        // ETHIOPIC SYLLABLE QYA..ETHIOPIC SYLLABLE QYO
        {0x2DC8, 0x2DCE},        // ETHIOPIC SYLLABLE KYA..ETHIOPIC SYLLABLE KYO
        {0x2DD0, 0x2DD6},        // ETHIOPIC SYLLABLE XYA..ETHIOPIC SYLLABLE XYO
        {0x2DD8, 0x2DDE},        // ETHIOPIC SYLLABLE GYA..ETHIOPIC SYLLABLE GYO
        {0x3005, 0x3005},        // IDEOGRAPHIC ITERATION MARK
        {0x3006, 0x3006},        // IDEOGRAPHIC CLOSING MARK
        {0x3007, 0x3007},        // IDEOGRAPHIC NUMBER ZERO
        {0x3021, 0x3029},        // HANGZHOU NUMERAL ONE..HANGZHOU NUMERAL NINE
        {0x3031, 0x3035},        // VERTICAL KANA REPEAT MARK..VERTICAL KANA REPEAT MARK LOWER HALF
        {0x3038, 0x303A},        // HANGZHOU NUMERAL TEN..HANGZHOU NUMERAL THIRTY
        {0x303B, 0x303B},        // VERTICAL IDEOGRAPHIC ITERATION MARK
        {0x303C, 0x303C},        // MASU MARK
        {0x3041, 0x3096},        // HIRAGANA LETTER SMALL A..HIRAGANA LETTER SMALL KE
        {0x309D, 0x309E},        // HIRAGANA ITERATION MARK..HIRAGANA VOICED ITERATION MARK
        {0x309F, 0x309F},        // HIRAGANA DIGRAPH YORI
        {0x30A1, 0x30FA},        // KATAKANA LETTER SMALL A..KATAKANA LETTER VO
        {0x30FC, 0x30FE},        // KATAKANA-HIRAGANA PROLONGED SOUND MARK..KATAKANA VOICED ITERATION MARK
        {0x30FF, 0x30FF},        // KATAKANA DIGRAPH KOTO
        {0x3105, 0x312C},        // BOPOMOFO LETTER B..BOPOMOFO LETTER GN
        {0x3131, 0x318E},        // HANGUL LETTER KIYEOK..HANGUL LETTER ARAEAE
        {0x31A0, 0x31B7},        // BOPOMOFO LETTER BU..BOPOMOFO FINAL LETTER H
        {0x31F0, 0x31FF},        // KATAKANA LETTER SMALL KU..KATAKANA LETTER SMALL RO
        {0x3400, 0x4DB5},        // CJK UNIFIED IDEOGRAPH-3400..CJK UNIFIED IDEOGRAPH-4DB5
        {0x4E00, 0x9FBB},        // CJK UNIFIED IDEOGRAPH-4E00..CJK UNIFIED IDEOGRAPH-9FBB
        {0xA000, 0xA014},        // YI SYLLABLE IT..YI SYLLABLE E
        {0xA015, 0xA015},        // YI SYLLABLE WU
        {0xA016, 0xA48C},        // YI SYLLABLE BIT..YI SYLLABLE YYR
        {0xA717, 0xA71A},        // MODIFIER LETTER DOT VERTICAL BAR..MODIFIER LETTER LOWER RIGHT CORNER ANGLE
        {0xA800, 0xA801},        // SYLOTI NAGRI LETTER A..SYLOTI NAGRI LETTER I
        {0xA803, 0xA805},        // SYLOTI NAGRI LETTER U..SYLOTI NAGRI LETTER O
        {0xA807, 0xA80A},        // SYLOTI NAGRI LETTER KO..SYLOTI NAGRI LETTER GHO
        {0xA80C, 0xA822},        // SYLOTI NAGRI LETTER CO..SYLOTI NAGRI LETTER HO
        {0xA840, 0xA873},        // PHAGS-PA LETTER KA..PHAGS-PA LETTER CANDRABINDU
        {0xAC00, 0xD7A3},        // HANGUL SYLLABLE GA..HANGUL SYLLABLE HIH
        {0xF900, 0xFA2D},        // CJK COMPATIBILITY IDEOGRAPH-F900..CJK COMPATIBILITY IDEOGRAPH-FA2D
        {0xFA30, 0xFA6A},        // CJK COMPATIBILITY IDEOGRAPH-FA30..CJK COMPATIBILITY IDEOGRAPH-FA6A
        {0xFA70, 0xFAD9},        // CJK COMPATIBILITY IDEOGRAPH-FA70..CJK COMPATIBILITY IDEOGRAPH-FAD9
        {0xFB00, 0xFB06},        // LATIN SMALL LIGATURE FF..LATIN SMALL LIGATURE ST
        {0xFB13, 0xFB17},        // ARMENIAN SMALL LIGATURE MEN NOW..ARMENIAN SMALL LIGATURE MEN XEH
        {0xFB1D, 0xFB1D},        // HEBREW LETTER YOD WITH HIRIQ
        {0xFB1F, 0xFB28},        // HEBREW LIGATURE YIDDISH YOD YOD PATAH..HEBREW LETTER WIDE TAV
        {0xFB2A, 0xFB36},        // HEBREW LETTER SHIN WITH SHIN DOT..HEBREW LETTER ZAYIN WITH DAGESH
        {0xFB38, 0xFB3C},        // HEBREW LETTER TET WITH DAGESH..HEBREW LETTER LAMED WITH DAGESH
        {0xFB3E, 0xFB3E},        // HEBREW LETTER MEM WITH DAGESH
        {0xFB40, 0xFB41},        // HEBREW LETTER NUN WITH DAGESH..HEBREW LETTER SAMEKH WITH DAGESH
        {0xFB43, 0xFB44},        // HEBREW LETTER FINAL PE WITH DAGESH..HEBREW LETTER PE WITH DAGESH
        {0xFB46, 0xFBB1},        // HEBREW LETTER TSADI WITH DAGESH..ARABIC LETTER YEH BARREE WITH HAMZA ABOVE FINAL FORM
        {0xFBD3, 0xFC5D},        // ARABIC LETTER NG ISOLATED FORM..ARABIC LIGATURE ALEF MAKSURA WITH SUPERSCRIPT ALEF ISOLATED FORM
        {0xFC64, 0xFD3D},        // ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH REH FINAL FORM..ARABIC LIGATURE ALEF WITH FATHATAN ISOLATED FORM
        {0xFD50, 0xFD8F},        // ARABIC LIGATURE TEH WITH JEEM WITH MEEM INITIAL FORM..ARABIC LIGATURE MEEM WITH KHAH WITH MEEM INITIAL FORM
        {0xFD92, 0xFDC7},        // ARABIC LIGATURE MEEM WITH JEEM WITH KHAH INITIAL FORM..ARABIC LIGATURE NOON WITH JEEM WITH YEH FINAL FORM
        {0xFDF0, 0xFDF9},        // ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN ISOLATED FORM..ARABIC LIGATURE SALLA ISOLATED FORM
        {0xFE71, 0xFE71},        // ARABIC TATWEEL WITH FATHATAN ABOVE
        {0xFE73, 0xFE73},        // ARABIC TAIL FRAGMENT
        {0xFE77, 0xFE77},        // ARABIC FATHA MEDIAL FORM
        {0xFE79, 0xFE79},        // ARABIC DAMMA MEDIAL FORM
        {0xFE7B, 0xFE7B},        // ARABIC KASRA MEDIAL FORM
        {0xFE7D, 0xFE7D},        // ARABIC SHADDA MEDIAL FORM
        {0xFE7F, 0xFEFC},        // ARABIC SUKUN MEDIAL FORM..ARABIC LIGATURE LAM WITH ALEF FINAL FORM
        {0xFF21, 0xFF3A},        // FULLWIDTH LATIN CAPITAL LETTER A..FULLWIDTH LATIN CAPITAL LETTER Z
        {0xFF41, 0xFF5A},        // FULLWIDTH LATIN SMALL LETTER A..FULLWIDTH LATIN SMALL LETTER Z
        {0xFF66, 0xFF6F},        // HALFWIDTH KATAKANA LETTER WO..HALFWIDTH KATAKANA LETTER SMALL TU
        {0xFF70, 0xFF70},        // HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
        {0xFF71, 0xFF9D},        // HALFWIDTH KATAKANA LETTER A..HALFWIDTH KATAKANA LETTER N
        {0xFFA0, 0xFFBE},        // HALFWIDTH HANGUL FILLER..HALFWIDTH HANGUL LETTER HIEUH
        {0xFFC2, 0xFFC7},        // HALFWIDTH HANGUL LETTER A..HALFWIDTH HANGUL LETTER E
        {0xFFCA, 0xFFCF},        // HALFWIDTH HANGUL LETTER YEO..HALFWIDTH HANGUL LETTER OE
        {0xFFD2, 0xFFD7},        // HALFWIDTH HANGUL LETTER YO..HALFWIDTH HANGUL LETTER YU
        {0xFFDA, 0xFFDC},        // HALFWIDTH HANGUL LETTER EU..HALFWIDTH HANGUL LETTER I
        {0x10000, 0x1000B},      // LINEAR B SYLLABLE B008 A..LINEAR B SYLLABLE B046 JE
        {0x1000D, 0x10026},      // LINEAR B SYLLABLE B036 JO..LINEAR B SYLLABLE B032 QO
        {0x10028, 0x1003A},      // LINEAR B SYLLABLE B060 RA..LINEAR B SYLLABLE B042 WO
        {0x1003C, 0x1003D},      // LINEAR B SYLLABLE B017 ZA..LINEAR B SYLLABLE B074 ZE
        {0x1003F, 0x1004D},      // LINEAR B SYLLABLE B020 ZO..LINEAR B SYLLABLE B091 TWO
        {0x10050, 0x1005D},      // LINEAR B SYMBOL B018..LINEAR B SYMBOL B089
        {0x10080, 0x100FA},      // LINEAR B IDEOGRAM B100 MAN..LINEAR B IDEOGRAM VESSEL B305
        {0x10140, 0x10174},      // GREEK ACROPHONIC ATTIC ONE QUARTER..GREEK ACROPHONIC STRATIAN FIFTY MNAS
        {0x10300, 0x1031E},      // OLD ITALIC LETTER A..OLD ITALIC LETTER UU
        {0x10330, 0x10340},      // GOTHIC LETTER AHSA..GOTHIC LETTER PAIRTHRA
        {0x10341, 0x10341},      // GOTHIC LETTER NINETY
        {0x10342, 0x10349},      // GOTHIC LETTER RAIDA..GOTHIC LETTER OTHAL
        {0x1034A, 0x1034A},      // GOTHIC LETTER NINE HUNDRED
        {0x10380, 0x1039D},      // UGARITIC LETTER ALPA..UGARITIC LETTER SSU
        {0x103A0, 0x103C3},      // OLD PERSIAN SIGN A..OLD PERSIAN SIGN HA
        {0x103C8, 0x103CF},      // OLD PERSIAN SIGN AURAMAZDAA..OLD PERSIAN SIGN BUUMISH
        {0x103D1, 0x103D5},      // OLD PERSIAN NUMBER ONE..OLD PERSIAN NUMBER HUNDRED
        {0x10400, 0x1044F},      // DESERET CAPITAL LETTER LONG I..DESERET SMALL LETTER EW
        {0x10450, 0x1049D},      // SHAVIAN LETTER PEEP..OSMANYA LETTER OO
        {0x10800, 0x10805},      // CYPRIOT SYLLABLE A..CYPRIOT SYLLABLE JA
        {0x10808, 0x10808},      // CYPRIOT SYLLABLE JO
        {0x1080A, 0x10835},      // CYPRIOT SYLLABLE KA..CYPRIOT SYLLABLE WO
        {0x10837, 0x10838},      // CYPRIOT SYLLABLE XA..CYPRIOT SYLLABLE XE
        {0x1083C, 0x1083C},      // CYPRIOT SYLLABLE ZA
        {0x1083F, 0x1083F},      // CYPRIOT SYLLABLE ZO
        {0x10900, 0x10915},      // PHOENICIAN LETTER ALF..PHOENICIAN LETTER TAU
        {0x10A00, 0x10A00},      // KHAROSHTHI LETTER A
        {0x10A10, 0x10A13},      // KHAROSHTHI LETTER KA..KHAROSHTHI LETTER GHA
        {0x10A15, 0x10A17},      // KHAROSHTHI LETTER CA..KHAROSHTHI LETTER JA
        {0x10A19, 0x10A33},      // KHAROSHTHI LETTER NYA..KHAROSHTHI LETTER TTTHA
        {0x12000, 0x1236E},      // CUNEIFORM SIGN A..CUNEIFORM SIGN ZUM
        {0x12400, 0x12462},      // CUNEIFORM NUMERIC SIGN TWO ASH..CUNEIFORM NUMERIC SIGN OLD ASSYRIAN ONE QUARTER
        {0x1D400, 0x1D454},      // MATHEMATICAL BOLD CAPITAL A..MATHEMATICAL ITALIC SMALL G
        {0x1D456, 0x1D49C},      // MATHEMATICAL ITALIC SMALL I..MATHEMATICAL SCRIPT CAPITAL A
        {0x1D49E, 0x1D49F},      // MATHEMATICAL SCRIPT CAPITAL C..MATHEMATICAL SCRIPT CAPITAL D
        {0x1D4A2, 0x1D4A2},      // MATHEMATICAL SCRIPT CAPITAL G
        {0x1D4A5, 0x1D4A6},      // MATHEMATICAL SCRIPT CAPITAL J..MATHEMATICAL SCRIPT CAPITAL K
        {0x1D4A9, 0x1D4AC},      // MATHEMATICAL SCRIPT CAPITAL N..MATHEMATICAL SCRIPT CAPITAL Q
        {0x1D4AE, 0x1D4B9},      // MATHEMATICAL SCRIPT CAPITAL S..MATHEMATICAL SCRIPT SMALL D
        {0x1D4BB, 0x1D4BB},      // MATHEMATICAL SCRIPT SMALL F
        {0x1D4BD, 0x1D4C3},      // MATHEMATICAL SCRIPT SMALL H..MATHEMATICAL SCRIPT SMALL N
        {0x1D4C5, 0x1D505},      // MATHEMATICAL SCRIPT SMALL P..MATHEMATICAL FRAKTUR CAPITAL B
        {0x1D507, 0x1D50A},      // MATHEMATICAL FRAKTUR CAPITAL D..MATHEMATICAL FRAKTUR CAPITAL G
        {0x1D50D, 0x1D514},      // MATHEMATICAL FRAKTUR CAPITAL J..MATHEMATICAL FRAKTUR CAPITAL Q
        {0x1D516, 0x1D51C},      // MATHEMATICAL FRAKTUR CAPITAL S..MATHEMATICAL FRAKTUR CAPITAL Y
        {0x1D51E, 0x1D539},      // MATHEMATICAL FRAKTUR SMALL A..MATHEMATICAL DOUBLE-STRUCK CAPITAL B
        {0x1D53B, 0x1D53E},      // MATHEMATICAL DOUBLE-STRUCK CAPITAL D..MATHEMATICAL DOUBLE-STRUCK CAPITAL G
        {0x1D540, 0x1D544},      // MATHEMATICAL DOUBLE-STRUCK CAPITAL I..MATHEMATICAL DOUBLE-STRUCK CAPITAL M
        {0x1D546, 0x1D546},      // MATHEMATICAL DOUBLE-STRUCK CAPITAL O
        {0x1D54A, 0x1D550},      // MATHEMATICAL DOUBLE-STRUCK CAPITAL S..MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
        {0x1D552, 0x1D6A5},      // MATHEMATICAL DOUBLE-STRUCK SMALL A..MATHEMATICAL ITALIC SMALL DOTLESS J
        {0x1D6A8, 0x1D6C0},      // MATHEMATICAL BOLD CAPITAL ALPHA..MATHEMATICAL BOLD CAPITAL OMEGA
        {0x1D6C2, 0x1D6DA},      // MATHEMATICAL BOLD SMALL ALPHA..MATHEMATICAL BOLD SMALL OMEGA
        {0x1D6DC, 0x1D6FA},      // MATHEMATICAL BOLD EPSILON SYMBOL..MATHEMATICAL ITALIC CAPITAL OMEGA
        {0x1D6FC, 0x1D714},      // MATHEMATICAL ITALIC SMALL ALPHA..MATHEMATICAL ITALIC SMALL OMEGA
        {0x1D716, 0x1D734},      // MATHEMATICAL ITALIC EPSILON SYMBOL..MATHEMATICAL BOLD ITALIC CAPITAL OMEGA
        {0x1D736, 0x1D74E},      // MATHEMATICAL BOLD ITALIC SMALL ALPHA..MATHEMATICAL BOLD ITALIC SMALL OMEGA
        {0x1D750, 0x1D76E},      // MATHEMATICAL BOLD ITALIC EPSILON SYMBOL..MATHEMATICAL SANS-SERIF BOLD CAPITAL OMEGA
        {0x1D770, 0x1D788},      // MATHEMATICAL SANS-SERIF BOLD SMALL ALPHA..MATHEMATICAL SANS-SERIF BOLD SMALL OMEGA
        {0x1D78A, 0x1D7A8},      // MATHEMATICAL SANS-SERIF BOLD EPSILON SYMBOL..MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMEGA
        {0x1D7AA, 0x1D7C2},      // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ALPHA..MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMEGA
        {0x1D7C4, 0x1D7CB},      // MATHEMATICAL SANS-SERIF BOLD ITALIC EPSILON SYMBOL..MATHEMATICAL BOLD SMALL DIGAMMA
        {0x20000, 0x2A6D6},      // CJK UNIFIED IDEOGRAPH-20000..CJK UNIFIED IDEOGRAPH-2A6D6
        {0x2F800, 0x2FA1D},      // CJK COMPATIBILITY IDEOGRAPH-2F800..CJK COMPATIBILITY IDEOGRAPH-2FA1D
        {0x0, 0x0}               // list terminator
    };
    static PropTable pattern( srcmap );
    return pattern.Lookup( ch );
}

bool Unicode::XID_Continue( uchar_t ch )
{
    PropRange srcmap[] = {
        {0x0030, 0x0039},        // DIGIT ZERO..DIGIT NINE
        {0x0041, 0x005A},        // LATIN CAPITAL LETTER A..LATIN CAPITAL LETTER Z
        {0x005F, 0x005F},        // LOW LINE (aka underscore)
        {0x0061, 0x007A},        // LATIN SMALL LETTER A..LATIN SMALL LETTER Z
        {0x00AA, 0x00AA},        // FEMININE ORDINAL INDICATOR
        {0x00B5, 0x00B5},        // MICRO SIGN
        {0x00B7, 0x00B7},        // MIDDLE DOT
        {0x00BA, 0x00BA},        // MASCULINE ORDINAL INDICATOR
        {0x00C0, 0x00D6},        // LATIN CAPITAL LETTER A WITH GRAVE..LATIN CAPITAL LETTER O WITH DIAERESIS
        {0x00D8, 0x00F6},        // LATIN CAPITAL LETTER O WITH STROKE..LATIN SMALL LETTER O WITH DIAERESIS
        {0x00F8, 0x01BA},        // LATIN SMALL LETTER O WITH STROKE..LATIN SMALL LETTER EZH WITH TAIL
        {0x01BB, 0x01BB},        // LATIN LETTER TWO WITH STROKE
        {0x01BC, 0x01BF},        // LATIN CAPITAL LETTER TONE FIVE..LATIN LETTER WYNN
        {0x01C0, 0x01C3},        // LATIN LETTER DENTAL CLICK..LATIN LETTER RETROFLEX CLICK
        {0x01C4, 0x0293},        // LATIN CAPITAL LETTER DZ WITH CARON..LATIN SMALL LETTER EZH WITH CURL
        {0x0294, 0x0294},        // LATIN LETTER GLOTTAL STOP
        {0x0295, 0x02AF},        // LATIN LETTER PHARYNGEAL VOICED FRICATIVE..LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL
        {0x02B0, 0x02C1},        // MODIFIER LETTER SMALL H..MODIFIER LETTER REVERSED GLOTTAL STOP
        {0x02C6, 0x02D1},        // MODIFIER LETTER CIRCUMFLEX ACCENT..MODIFIER LETTER HALF TRIANGULAR COLON
        {0x02E0, 0x02E4},        // MODIFIER LETTER SMALL GAMMA..MODIFIER LETTER SMALL REVERSED GLOTTAL STOP
        {0x02EE, 0x02EE},        // MODIFIER LETTER DOUBLE APOSTROPHE
        {0x0300, 0x036F},        // COMBINING GRAVE ACCENT..COMBINING LATIN SMALL LETTER X
        {0x037B, 0x037D},        // GREEK SMALL REVERSED LUNATE SIGMA SYMBOL..GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
        {0x0386, 0x0386},        // GREEK CAPITAL LETTER ALPHA WITH TONOS
        {0x0388, 0x038A},        // GREEK CAPITAL LETTER EPSILON WITH TONOS..GREEK CAPITAL LETTER IOTA WITH TONOS
        {0x038C, 0x038C},        // GREEK CAPITAL LETTER OMICRON WITH TONOS
        {0x038E, 0x03A1},        // GREEK CAPITAL LETTER UPSILON WITH TONOS..GREEK CAPITAL LETTER RHO
        {0x03A3, 0x03CE},        // GREEK CAPITAL LETTER SIGMA..GREEK SMALL LETTER OMEGA WITH TONOS
        {0x03D0, 0x03F5},        // GREEK BETA SYMBOL..GREEK LUNATE EPSILON SYMBOL
        {0x03F7, 0x0481},        // GREEK CAPITAL LETTER SHO..CYRILLIC SMALL LETTER KOPPA
        {0x0483, 0x0486},        // COMBINING CYRILLIC TITLO..COMBINING CYRILLIC PSILI PNEUMATA
        {0x048A, 0x0513},        // CYRILLIC CAPITAL LETTER SHORT I WITH TAIL..CYRILLIC SMALL LETTER EL WITH HOOK
        {0x0531, 0x0556},        // ARMENIAN CAPITAL LETTER AYB..ARMENIAN CAPITAL LETTER FEH
        {0x0559, 0x0559},        // ARMENIAN MODIFIER LETTER LEFT HALF RING
        {0x0561, 0x0587},        // ARMENIAN SMALL LETTER AYB..ARMENIAN SMALL LIGATURE ECH YIWN
        {0x0591, 0x05BD},        // HEBREW ACCENT ETNAHTA..HEBREW POINT METEG
        {0x05BF, 0x05BF},        // HEBREW POINT RAFE
        {0x05C1, 0x05C2},        // HEBREW POINT SHIN DOT..HEBREW POINT SIN DOT
        {0x05C4, 0x05C5},        // HEBREW MARK UPPER DOT..HEBREW MARK LOWER DOT
        {0x05C7, 0x05C7},        // HEBREW POINT QAMATS QATAN
        {0x05D0, 0x05EA},        // HEBREW LETTER ALEF..HEBREW LETTER TAV
        {0x05F0, 0x05F2},        // HEBREW LIGATURE YIDDISH DOUBLE VAV..HEBREW LIGATURE YIDDISH DOUBLE YOD
        {0x0610, 0x0615},        // ARABIC SIGN SALLALLAHOU ALAYHE WASSALLAM..ARABIC SMALL HIGH TAH
        {0x0621, 0x063A},        // ARABIC LETTER HAMZA..ARABIC LETTER GHAIN
        {0x0640, 0x0640},        // ARABIC TATWEEL
        {0x0641, 0x064A},        // ARABIC LETTER FEH..ARABIC LETTER YEH
        {0x064B, 0x065E},        // ARABIC FATHATAN..ARABIC FATHA WITH TWO DOTS
        {0x0660, 0x0669},        // ARABIC-INDIC DIGIT ZERO..ARABIC-INDIC DIGIT NINE
        {0x066E, 0x066F},        // ARABIC LETTER DOTLESS BEH..ARABIC LETTER DOTLESS QAF
        {0x0670, 0x0670},        // ARABIC LETTER SUPERSCRIPT ALEF
        {0x0671, 0x06D3},        // ARABIC LETTER ALEF WASLA..ARABIC LETTER YEH BARREE WITH HAMZA ABOVE
        {0x06D5, 0x06D5},        // ARABIC LETTER AE
        {0x06D6, 0x06DC},        // ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA..ARABIC SMALL HIGH SEEN
        {0x06DF, 0x06E4},        // ARABIC SMALL HIGH ROUNDED ZERO..ARABIC SMALL HIGH MADDA
        {0x06E5, 0x06E6},        // ARABIC SMALL WAW..ARABIC SMALL YEH
        {0x06E7, 0x06E8},        // ARABIC SMALL HIGH YEH..ARABIC SMALL HIGH NOON
        {0x06EA, 0x06ED},        // ARABIC EMPTY CENTRE LOW STOP..ARABIC SMALL LOW MEEM
        {0x06EE, 0x06EF},        // ARABIC LETTER DAL WITH INVERTED V..ARABIC LETTER REH WITH INVERTED V
        {0x06F0, 0x06F9},        // EXTENDED ARABIC-INDIC DIGIT ZERO..EXTENDED ARABIC-INDIC DIGIT NINE
        {0x06FA, 0x06FC},        // ARABIC LETTER SHEEN WITH DOT BELOW..ARABIC LETTER GHAIN WITH DOT BELOW
        {0x06FF, 0x06FF},        // ARABIC LETTER HEH WITH INVERTED V
        {0x0710, 0x0710},        // SYRIAC LETTER ALAPH
        {0x0711, 0x0711},        // SYRIAC LETTER SUPERSCRIPT ALAPH
        {0x0712, 0x072F},        // SYRIAC LETTER BETH..SYRIAC LETTER PERSIAN DHALATH
        {0x0730, 0x074A},        // SYRIAC PTHAHA ABOVE..SYRIAC BARREKH
        {0x074D, 0x076D},        // SYRIAC LETTER SOGDIAN ZHAIN..ARABIC LETTER SEEN WITH TWO DOTS VERTICALLY ABOVE
        {0x0780, 0x07A5},        // THAANA LETTER HAA..THAANA LETTER WAAVU
        {0x07A6, 0x07B0},        // THAANA ABAFILI..THAANA SUKUN
        {0x07B1, 0x07B1},        // THAANA LETTER NAA
        {0x07C0, 0x07C9},        // NKO DIGIT ZERO..NKO DIGIT NINE
        {0x07CA, 0x07EA},        // NKO LETTER A..NKO LETTER JONA RA
        {0x07EB, 0x07F3},        // NKO COMBINING SHORT HIGH TONE..NKO COMBINING DOUBLE DOT ABOVE
        {0x07F4, 0x07F5},        // NKO HIGH TONE APOSTROPHE..NKO LOW TONE APOSTROPHE
        {0x07FA, 0x07FA},        // NKO LAJANYALAN
        {0x0901, 0x0902},        // DEVANAGARI SIGN CANDRABINDU..DEVANAGARI SIGN ANUSVARA
        {0x0903, 0x0903},        // DEVANAGARI SIGN VISARGA
        {0x0904, 0x0939},        // DEVANAGARI LETTER SHORT A..DEVANAGARI LETTER HA
        {0x093C, 0x093C},        // DEVANAGARI SIGN NUKTA
        {0x093D, 0x093D},        // DEVANAGARI SIGN AVAGRAHA
        {0x093E, 0x0940},        // DEVANAGARI VOWEL SIGN AA..DEVANAGARI VOWEL SIGN II
        {0x0941, 0x0948},        // DEVANAGARI VOWEL SIGN U..DEVANAGARI VOWEL SIGN AI
        {0x0949, 0x094C},        // DEVANAGARI VOWEL SIGN CANDRA O..DEVANAGARI VOWEL SIGN AU
        {0x094D, 0x094D},        // DEVANAGARI SIGN VIRAMA
        {0x0950, 0x0950},        // DEVANAGARI OM
        {0x0951, 0x0954},        // DEVANAGARI STRESS SIGN UDATTA..DEVANAGARI ACUTE ACCENT
        {0x0958, 0x0961},        // DEVANAGARI LETTER QA..DEVANAGARI LETTER VOCALIC LL
        {0x0962, 0x0963},        // DEVANAGARI VOWEL SIGN VOCALIC L..DEVANAGARI VOWEL SIGN VOCALIC LL
        {0x0966, 0x096F},        // DEVANAGARI DIGIT ZERO..DEVANAGARI DIGIT NINE
        {0x097B, 0x097F},        // DEVANAGARI LETTER GGA..DEVANAGARI LETTER BBA
        {0x0981, 0x0981},        // BENGALI SIGN CANDRABINDU
        {0x0982, 0x0983},        // BENGALI SIGN ANUSVARA..BENGALI SIGN VISARGA
        {0x0985, 0x098C},        // BENGALI LETTER A..BENGALI LETTER VOCALIC L
        {0x098F, 0x0990},        // BENGALI LETTER E..BENGALI LETTER AI
        {0x0993, 0x09A8},        // BENGALI LETTER O..BENGALI LETTER NA
        {0x09AA, 0x09B0},        // BENGALI LETTER PA..BENGALI LETTER RA
        {0x09B2, 0x09B2},        // BENGALI LETTER LA
        {0x09B6, 0x09B9},        // BENGALI LETTER SHA..BENGALI LETTER HA
        {0x09BC, 0x09BC},        // BENGALI SIGN NUKTA
        {0x09BD, 0x09BD},        // BENGALI SIGN AVAGRAHA
        {0x09BE, 0x09C0},        // BENGALI VOWEL SIGN AA..BENGALI VOWEL SIGN II
        {0x09C1, 0x09C4},        // BENGALI VOWEL SIGN U..BENGALI VOWEL SIGN VOCALIC RR
        {0x09C7, 0x09C8},        // BENGALI VOWEL SIGN E..BENGALI VOWEL SIGN AI
        {0x09CB, 0x09CC},        // BENGALI VOWEL SIGN O..BENGALI VOWEL SIGN AU
        {0x09CD, 0x09CD},        // BENGALI SIGN VIRAMA
        {0x09CE, 0x09CE},        // BENGALI LETTER KHANDA TA
        {0x09D7, 0x09D7},        // BENGALI AU LENGTH MARK
        {0x09DC, 0x09DD},        // BENGALI LETTER RRA..BENGALI LETTER RHA
        {0x09DF, 0x09E1},        // BENGALI LETTER YYA..BENGALI LETTER VOCALIC LL
        {0x09E2, 0x09E3},        // BENGALI VOWEL SIGN VOCALIC L..BENGALI VOWEL SIGN VOCALIC LL
        {0x09E6, 0x09EF},        // BENGALI DIGIT ZERO..BENGALI DIGIT NINE
        {0x09F0, 0x09F1},        // BENGALI LETTER RA WITH MIDDLE DIAGONAL..BENGALI LETTER RA WITH LOWER DIAGONAL
        {0x0A01, 0x0A02},        // GURMUKHI SIGN ADAK BINDI..GURMUKHI SIGN BINDI
        {0x0A03, 0x0A03},        // GURMUKHI SIGN VISARGA
        {0x0A05, 0x0A0A},        // GURMUKHI LETTER A..GURMUKHI LETTER UU
        {0x0A0F, 0x0A10},        // GURMUKHI LETTER EE..GURMUKHI LETTER AI
        {0x0A13, 0x0A28},        // GURMUKHI LETTER OO..GURMUKHI LETTER NA
        {0x0A2A, 0x0A30},        // GURMUKHI LETTER PA..GURMUKHI LETTER RA
        {0x0A32, 0x0A33},        // GURMUKHI LETTER LA..GURMUKHI LETTER LLA
        {0x0A35, 0x0A36},        // GURMUKHI LETTER VA..GURMUKHI LETTER SHA
        {0x0A38, 0x0A39},        // GURMUKHI LETTER SA..GURMUKHI LETTER HA
        {0x0A3C, 0x0A3C},        // GURMUKHI SIGN NUKTA
        {0x0A3E, 0x0A40},        // GURMUKHI VOWEL SIGN AA..GURMUKHI VOWEL SIGN II
        {0x0A41, 0x0A42},        // GURMUKHI VOWEL SIGN U..GURMUKHI VOWEL SIGN UU
        {0x0A47, 0x0A48},        // GURMUKHI VOWEL SIGN EE..GURMUKHI VOWEL SIGN AI
        {0x0A4B, 0x0A4D},        // GURMUKHI VOWEL SIGN OO..GURMUKHI SIGN VIRAMA
        {0x0A59, 0x0A5C},        // GURMUKHI LETTER KHHA..GURMUKHI LETTER RRA
        {0x0A5E, 0x0A5E},        // GURMUKHI LETTER FA
        {0x0A66, 0x0A6F},        // GURMUKHI DIGIT ZERO..GURMUKHI DIGIT NINE
        {0x0A70, 0x0A71},        // GURMUKHI TIPPI..GURMUKHI ADDAK
        {0x0A72, 0x0A74},        // GURMUKHI IRI..GURMUKHI EK ONKAR
        {0x0A81, 0x0A82},        // GUJARATI SIGN CANDRABINDU..GUJARATI SIGN ANUSVARA
        {0x0A83, 0x0A83},        // GUJARATI SIGN VISARGA
        {0x0A85, 0x0A8D},        // GUJARATI LETTER A..GUJARATI VOWEL CANDRA E
        {0x0A8F, 0x0A91},        // GUJARATI LETTER E..GUJARATI VOWEL CANDRA O
        {0x0A93, 0x0AA8},        // GUJARATI LETTER O..GUJARATI LETTER NA
        {0x0AAA, 0x0AB0},        // GUJARATI LETTER PA..GUJARATI LETTER RA
        {0x0AB2, 0x0AB3},        // GUJARATI LETTER LA..GUJARATI LETTER LLA
        {0x0AB5, 0x0AB9},        // GUJARATI LETTER VA..GUJARATI LETTER HA
        {0x0ABC, 0x0ABC},        // GUJARATI SIGN NUKTA
        {0x0ABD, 0x0ABD},        // GUJARATI SIGN AVAGRAHA
        {0x0ABE, 0x0AC0},        // GUJARATI VOWEL SIGN AA..GUJARATI VOWEL SIGN II
        {0x0AC1, 0x0AC5},        // GUJARATI VOWEL SIGN U..GUJARATI VOWEL SIGN CANDRA E
        {0x0AC7, 0x0AC8},        // GUJARATI VOWEL SIGN E..GUJARATI VOWEL SIGN AI
        {0x0AC9, 0x0AC9},        // GUJARATI VOWEL SIGN CANDRA O
        {0x0ACB, 0x0ACC},        // GUJARATI VOWEL SIGN O..GUJARATI VOWEL SIGN AU
        {0x0ACD, 0x0ACD},        // GUJARATI SIGN VIRAMA
        {0x0AD0, 0x0AD0},        // GUJARATI OM
        {0x0AE0, 0x0AE1},        // GUJARATI LETTER VOCALIC RR..GUJARATI LETTER VOCALIC LL
        {0x0AE2, 0x0AE3},        // GUJARATI VOWEL SIGN VOCALIC L..GUJARATI VOWEL SIGN VOCALIC LL
        {0x0AE6, 0x0AEF},        // GUJARATI DIGIT ZERO..GUJARATI DIGIT NINE
        {0x0B01, 0x0B01},        // ORIYA SIGN CANDRABINDU
        {0x0B02, 0x0B03},        // ORIYA SIGN ANUSVARA..ORIYA SIGN VISARGA
        {0x0B05, 0x0B0C},        // ORIYA LETTER A..ORIYA LETTER VOCALIC L
        {0x0B0F, 0x0B10},        // ORIYA LETTER E..ORIYA LETTER AI
        {0x0B13, 0x0B28},        // ORIYA LETTER O..ORIYA LETTER NA
        {0x0B2A, 0x0B30},        // ORIYA LETTER PA..ORIYA LETTER RA
        {0x0B32, 0x0B33},        // ORIYA LETTER LA..ORIYA LETTER LLA
        {0x0B35, 0x0B39},        // ORIYA LETTER VA..ORIYA LETTER HA
        {0x0B3C, 0x0B3C},        // ORIYA SIGN NUKTA
        {0x0B3D, 0x0B3D},        // ORIYA SIGN AVAGRAHA
        {0x0B3E, 0x0B3E},        // ORIYA VOWEL SIGN AA
        {0x0B3F, 0x0B3F},        // ORIYA VOWEL SIGN I
        {0x0B40, 0x0B40},        // ORIYA VOWEL SIGN II
        {0x0B41, 0x0B43},        // ORIYA VOWEL SIGN U..ORIYA VOWEL SIGN VOCALIC R
        {0x0B47, 0x0B48},        // ORIYA VOWEL SIGN E..ORIYA VOWEL SIGN AI
        {0x0B4B, 0x0B4C},        // ORIYA VOWEL SIGN O..ORIYA VOWEL SIGN AU
        {0x0B4D, 0x0B4D},        // ORIYA SIGN VIRAMA
        {0x0B56, 0x0B56},        // ORIYA AI LENGTH MARK
        {0x0B57, 0x0B57},        // ORIYA AU LENGTH MARK
        {0x0B5C, 0x0B5D},        // ORIYA LETTER RRA..ORIYA LETTER RHA
        {0x0B5F, 0x0B61},        // ORIYA LETTER YYA..ORIYA LETTER VOCALIC LL
        {0x0B66, 0x0B6F},        // ORIYA DIGIT ZERO..ORIYA DIGIT NINE
        {0x0B71, 0x0B71},        // ORIYA LETTER WA
        {0x0B82, 0x0B82},        // TAMIL SIGN ANUSVARA
        {0x0B83, 0x0B83},        // TAMIL SIGN VISARGA
        {0x0B85, 0x0B8A},        // TAMIL LETTER A..TAMIL LETTER UU
        {0x0B8E, 0x0B90},        // TAMIL LETTER E..TAMIL LETTER AI
        {0x0B92, 0x0B95},        // TAMIL LETTER O..TAMIL LETTER KA
        {0x0B99, 0x0B9A},        // TAMIL LETTER NGA..TAMIL LETTER CA
        {0x0B9C, 0x0B9C},        // TAMIL LETTER JA
        {0x0B9E, 0x0B9F},        // TAMIL LETTER NYA..TAMIL LETTER TTA
        {0x0BA3, 0x0BA4},        // TAMIL LETTER NNA..TAMIL LETTER TA
        {0x0BA8, 0x0BAA},        // TAMIL LETTER NA..TAMIL LETTER PA
        {0x0BAE, 0x0BB9},        // TAMIL LETTER MA..TAMIL LETTER HA
        {0x0BBE, 0x0BBF},        // TAMIL VOWEL SIGN AA..TAMIL VOWEL SIGN I
        {0x0BC0, 0x0BC0},        // TAMIL VOWEL SIGN II
        {0x0BC1, 0x0BC2},        // TAMIL VOWEL SIGN U..TAMIL VOWEL SIGN UU
        {0x0BC6, 0x0BC8},        // TAMIL VOWEL SIGN E..TAMIL VOWEL SIGN AI
        {0x0BCA, 0x0BCC},        // TAMIL VOWEL SIGN O..TAMIL VOWEL SIGN AU
        {0x0BCD, 0x0BCD},        // TAMIL SIGN VIRAMA
        {0x0BD7, 0x0BD7},        // TAMIL AU LENGTH MARK
        {0x0BE6, 0x0BEF},        // TAMIL DIGIT ZERO..TAMIL DIGIT NINE
        {0x0C01, 0x0C03},        // TELUGU SIGN CANDRABINDU..TELUGU SIGN VISARGA
        {0x0C05, 0x0C0C},        // TELUGU LETTER A..TELUGU LETTER VOCALIC L
        {0x0C0E, 0x0C10},        // TELUGU LETTER E..TELUGU LETTER AI
        {0x0C12, 0x0C28},        // TELUGU LETTER O..TELUGU LETTER NA
        {0x0C2A, 0x0C33},        // TELUGU LETTER PA..TELUGU LETTER LLA
        {0x0C35, 0x0C39},        // TELUGU LETTER VA..TELUGU LETTER HA
        {0x0C3E, 0x0C40},        // TELUGU VOWEL SIGN AA..TELUGU VOWEL SIGN II
        {0x0C41, 0x0C44},        // TELUGU VOWEL SIGN U..TELUGU VOWEL SIGN VOCALIC RR
        {0x0C46, 0x0C48},        // TELUGU VOWEL SIGN E..TELUGU VOWEL SIGN AI
        {0x0C4A, 0x0C4D},        // TELUGU VOWEL SIGN O..TELUGU SIGN VIRAMA
        {0x0C55, 0x0C56},        // TELUGU LENGTH MARK..TELUGU AI LENGTH MARK
        {0x0C60, 0x0C61},        // TELUGU LETTER VOCALIC RR..TELUGU LETTER VOCALIC LL
        {0x0C66, 0x0C6F},        // TELUGU DIGIT ZERO..TELUGU DIGIT NINE
        {0x0C82, 0x0C83},        // KANNADA SIGN ANUSVARA..KANNADA SIGN VISARGA
        {0x0C85, 0x0C8C},        // KANNADA LETTER A..KANNADA LETTER VOCALIC L
        {0x0C8E, 0x0C90},        // KANNADA LETTER E..KANNADA LETTER AI
        {0x0C92, 0x0CA8},        // KANNADA LETTER O..KANNADA LETTER NA
        {0x0CAA, 0x0CB3},        // KANNADA LETTER PA..KANNADA LETTER LLA
        {0x0CB5, 0x0CB9},        // KANNADA LETTER VA..KANNADA LETTER HA
        {0x0CBC, 0x0CBC},        // KANNADA SIGN NUKTA
        {0x0CBD, 0x0CBD},        // KANNADA SIGN AVAGRAHA
        {0x0CBE, 0x0CBE},        // KANNADA VOWEL SIGN AA
        {0x0CBF, 0x0CBF},        // KANNADA VOWEL SIGN I
        {0x0CC0, 0x0CC4},        // KANNADA VOWEL SIGN II..KANNADA VOWEL SIGN VOCALIC RR
        {0x0CC6, 0x0CC6},        // KANNADA VOWEL SIGN E
        {0x0CC7, 0x0CC8},        // KANNADA VOWEL SIGN EE..KANNADA VOWEL SIGN AI
        {0x0CCA, 0x0CCB},        // KANNADA VOWEL SIGN O..KANNADA VOWEL SIGN OO
        {0x0CCC, 0x0CCD},        // KANNADA VOWEL SIGN AU..KANNADA SIGN VIRAMA
        {0x0CD5, 0x0CD6},        // KANNADA LENGTH MARK..KANNADA AI LENGTH MARK
        {0x0CDE, 0x0CDE},        // KANNADA LETTER FA
        {0x0CE0, 0x0CE1},        // KANNADA LETTER VOCALIC RR..KANNADA LETTER VOCALIC LL
        {0x0CE2, 0x0CE3},        // KANNADA VOWEL SIGN VOCALIC L..KANNADA VOWEL SIGN VOCALIC LL
        {0x0CE6, 0x0CEF},        // KANNADA DIGIT ZERO..KANNADA DIGIT NINE
        {0x0D02, 0x0D03},        // MALAYALAM SIGN ANUSVARA..MALAYALAM SIGN VISARGA
        {0x0D05, 0x0D0C},        // MALAYALAM LETTER A..MALAYALAM LETTER VOCALIC L
        {0x0D0E, 0x0D10},        // MALAYALAM LETTER E..MALAYALAM LETTER AI
        {0x0D12, 0x0D28},        // MALAYALAM LETTER O..MALAYALAM LETTER NA
        {0x0D2A, 0x0D39},        // MALAYALAM LETTER PA..MALAYALAM LETTER HA
        {0x0D3E, 0x0D40},        // MALAYALAM VOWEL SIGN AA..MALAYALAM VOWEL SIGN II
        {0x0D41, 0x0D43},        // MALAYALAM VOWEL SIGN U..MALAYALAM VOWEL SIGN VOCALIC R
        {0x0D46, 0x0D48},        // MALAYALAM VOWEL SIGN E..MALAYALAM VOWEL SIGN AI
        {0x0D4A, 0x0D4C},        // MALAYALAM VOWEL SIGN O..MALAYALAM VOWEL SIGN AU
        {0x0D4D, 0x0D4D},        // MALAYALAM SIGN VIRAMA
        {0x0D57, 0x0D57},        // MALAYALAM AU LENGTH MARK
        {0x0D60, 0x0D61},        // MALAYALAM LETTER VOCALIC RR..MALAYALAM LETTER VOCALIC LL
        {0x0D66, 0x0D6F},        // MALAYALAM DIGIT ZERO..MALAYALAM DIGIT NINE
        {0x0D82, 0x0D83},        // SINHALA SIGN ANUSVARAYA..SINHALA SIGN VISARGAYA
        {0x0D85, 0x0D96},        // SINHALA LETTER AYANNA..SINHALA LETTER AUYANNA
        {0x0D9A, 0x0DB1},        // SINHALA LETTER ALPAPRAANA KAYANNA..SINHALA LETTER DANTAJA NAYANNA
        {0x0DB3, 0x0DBB},        // SINHALA LETTER SANYAKA DAYANNA..SINHALA LETTER RAYANNA
        {0x0DBD, 0x0DBD},        // SINHALA LETTER DANTAJA LAYANNA
        {0x0DC0, 0x0DC6},        // SINHALA LETTER VAYANNA..SINHALA LETTER FAYANNA
        {0x0DCA, 0x0DCA},        // SINHALA SIGN AL-LAKUNA
        {0x0DCF, 0x0DD1},        // SINHALA VOWEL SIGN AELA-PILLA..SINHALA VOWEL SIGN DIGA AEDA-PILLA
        {0x0DD2, 0x0DD4},        // SINHALA VOWEL SIGN KETTI IS-PILLA..SINHALA VOWEL SIGN KETTI PAA-PILLA
        {0x0DD6, 0x0DD6},        // SINHALA VOWEL SIGN DIGA PAA-PILLA
        {0x0DD8, 0x0DDF},        // SINHALA VOWEL SIGN GAETTA-PILLA..SINHALA VOWEL SIGN GAYANUKITTA
        {0x0DF2, 0x0DF3},        // SINHALA VOWEL SIGN DIGA GAETTA-PILLA..SINHALA VOWEL SIGN DIGA GAYANUKITTA
        {0x0E01, 0x0E30},        // THAI CHARACTER KO KAI..THAI CHARACTER SARA A
        {0x0E31, 0x0E31},        // THAI CHARACTER MAI HAN-AKAT
        {0x0E32, 0x0E33},        // THAI CHARACTER SARA AA..THAI CHARACTER SARA AM
        {0x0E34, 0x0E3A},        // THAI CHARACTER SARA I..THAI CHARACTER PHINTHU
        {0x0E40, 0x0E45},        // THAI CHARACTER SARA E..THAI CHARACTER LAKKHANGYAO
        {0x0E46, 0x0E46},        // THAI CHARACTER MAIYAMOK
        {0x0E47, 0x0E4E},        // THAI CHARACTER MAITAIKHU..THAI CHARACTER YAMAKKAN
        {0x0E50, 0x0E59},        // THAI DIGIT ZERO..THAI DIGIT NINE
        {0x0E81, 0x0E82},        // LAO LETTER KO..LAO LETTER KHO SUNG
        {0x0E84, 0x0E84},        // LAO LETTER KHO TAM
        {0x0E87, 0x0E88},        // LAO LETTER NGO..LAO LETTER CO
        {0x0E8A, 0x0E8A},        // LAO LETTER SO TAM
        {0x0E8D, 0x0E8D},        // LAO LETTER NYO
        {0x0E94, 0x0E97},        // LAO LETTER DO..LAO LETTER THO TAM
        {0x0E99, 0x0E9F},        // LAO LETTER NO..LAO LETTER FO SUNG
        {0x0EA1, 0x0EA3},        // LAO LETTER MO..LAO LETTER LO LING
        {0x0EA5, 0x0EA5},        // LAO LETTER LO LOOT
        {0x0EA7, 0x0EA7},        // LAO LETTER WO
        {0x0EAA, 0x0EAB},        // LAO LETTER SO SUNG..LAO LETTER HO SUNG
        {0x0EAD, 0x0EB0},        // LAO LETTER O..LAO VOWEL SIGN A
        {0x0EB1, 0x0EB1},        // LAO VOWEL SIGN MAI KAN
        {0x0EB2, 0x0EB3},        // LAO VOWEL SIGN AA..LAO VOWEL SIGN AM
        {0x0EB4, 0x0EB9},        // LAO VOWEL SIGN I..LAO VOWEL SIGN UU
        {0x0EBB, 0x0EBC},        // LAO VOWEL SIGN MAI KON..LAO SEMIVOWEL SIGN LO
        {0x0EBD, 0x0EBD},        // LAO SEMIVOWEL SIGN NYO
        {0x0EC0, 0x0EC4},        // LAO VOWEL SIGN E..LAO VOWEL SIGN AI
        {0x0EC6, 0x0EC6},        // LAO KO LA
        {0x0EC8, 0x0ECD},        // LAO TONE MAI EK..LAO NIGGAHITA
        {0x0ED0, 0x0ED9},        // LAO DIGIT ZERO..LAO DIGIT NINE
        {0x0EDC, 0x0EDD},        // LAO HO NO..LAO HO MO
        {0x0F00, 0x0F00},        // TIBETAN SYLLABLE OM
        {0x0F18, 0x0F19},        // TIBETAN ASTROLOGICAL SIGN -KHYUD PA..TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS
        {0x0F20, 0x0F29},        // TIBETAN DIGIT ZERO..TIBETAN DIGIT NINE
        {0x0F35, 0x0F35},        // TIBETAN MARK NGAS BZUNG NYI ZLA
        {0x0F37, 0x0F37},        // TIBETAN MARK NGAS BZUNG SGOR RTAGS
        {0x0F39, 0x0F39},        // TIBETAN MARK TSA -PHRU
        {0x0F3E, 0x0F3F},        // TIBETAN SIGN YAR TSHES..TIBETAN SIGN MAR TSHES
        {0x0F40, 0x0F47},        // TIBETAN LETTER KA..TIBETAN LETTER JA
        {0x0F49, 0x0F6A},        // TIBETAN LETTER NYA..TIBETAN LETTER FIXED-FORM RA
        {0x0F71, 0x0F7E},        // TIBETAN VOWEL SIGN AA..TIBETAN SIGN RJES SU NGA RO
        {0x0F7F, 0x0F7F},        // TIBETAN SIGN RNAM BCAD
        {0x0F80, 0x0F84},        // TIBETAN VOWEL SIGN REVERSED I..TIBETAN MARK HALANTA
        {0x0F86, 0x0F87},        // TIBETAN SIGN LCI RTAGS..TIBETAN SIGN YANG RTAGS
        {0x0F88, 0x0F8B},        // TIBETAN SIGN LCE TSA CAN..TIBETAN SIGN GRU MED RGYINGS
        {0x0F90, 0x0F97},        // TIBETAN SUBJOINED LETTER KA..TIBETAN SUBJOINED LETTER JA
        {0x0F99, 0x0FBC},        // TIBETAN SUBJOINED LETTER NYA..TIBETAN SUBJOINED LETTER FIXED-FORM RA
        {0x0FC6, 0x0FC6},        // TIBETAN SYMBOL PADMA GDAN
        {0x1000, 0x1021},        // MYANMAR LETTER KA..MYANMAR LETTER A
        {0x1023, 0x1027},        // MYANMAR LETTER I..MYANMAR LETTER E
        {0x1029, 0x102A},        // MYANMAR LETTER O..MYANMAR LETTER AU
        {0x102C, 0x102C},        // MYANMAR VOWEL SIGN AA
        {0x102D, 0x1030},        // MYANMAR VOWEL SIGN I..MYANMAR VOWEL SIGN UU
        {0x1031, 0x1031},        // MYANMAR VOWEL SIGN E
        {0x1032, 0x1032},        // MYANMAR VOWEL SIGN AI
        {0x1036, 0x1037},        // MYANMAR SIGN ANUSVARA..MYANMAR SIGN DOT BELOW
        {0x1038, 0x1038},        // MYANMAR SIGN VISARGA
        {0x1039, 0x1039},        // MYANMAR SIGN VIRAMA
        {0x1040, 0x1049},        // MYANMAR DIGIT ZERO..MYANMAR DIGIT NINE
        {0x1050, 0x1055},        // MYANMAR LETTER SHA..MYANMAR LETTER VOCALIC LL
        {0x1056, 0x1057},        // MYANMAR VOWEL SIGN VOCALIC R..MYANMAR VOWEL SIGN VOCALIC RR
        {0x1058, 0x1059},        // MYANMAR VOWEL SIGN VOCALIC L..MYANMAR VOWEL SIGN VOCALIC LL
        {0x10A0, 0x10C5},        // GEORGIAN CAPITAL LETTER AN..GEORGIAN CAPITAL LETTER HOE
        {0x10D0, 0x10FA},        // GEORGIAN LETTER AN..GEORGIAN LETTER AIN
        {0x10FC, 0x10FC},        // MODIFIER LETTER GEORGIAN NAR
        {0x1100, 0x1159},        // HANGUL CHOSEONG KIYEOK..HANGUL CHOSEONG YEORINHIEUH
        {0x115F, 0x11A2},        // HANGUL CHOSEONG FILLER..HANGUL JUNGSEONG SSANGARAEA
        {0x11A8, 0x11F9},        // HANGUL JONGSEONG KIYEOK..HANGUL JONGSEONG YEORINHIEUH
        {0x1200, 0x1248},        // ETHIOPIC SYLLABLE HA..ETHIOPIC SYLLABLE QWA
        {0x124A, 0x124D},        // ETHIOPIC SYLLABLE QWI..ETHIOPIC SYLLABLE QWE
        {0x1250, 0x1256},        // ETHIOPIC SYLLABLE QHA..ETHIOPIC SYLLABLE QHO
        {0x1258, 0x1258},        // ETHIOPIC SYLLABLE QHWA
        {0x125A, 0x125D},        // ETHIOPIC SYLLABLE QHWI..ETHIOPIC SYLLABLE QHWE
        {0x1260, 0x1288},        // ETHIOPIC SYLLABLE BA..ETHIOPIC SYLLABLE XWA
        {0x128A, 0x128D},        // ETHIOPIC SYLLABLE XWI..ETHIOPIC SYLLABLE XWE
        {0x1290, 0x12B0},        // ETHIOPIC SYLLABLE NA..ETHIOPIC SYLLABLE KWA
        {0x12B2, 0x12B5},        // ETHIOPIC SYLLABLE KWI..ETHIOPIC SYLLABLE KWE
        {0x12B8, 0x12BE},        // ETHIOPIC SYLLABLE KXA..ETHIOPIC SYLLABLE KXO
        {0x12C0, 0x12C0},        // ETHIOPIC SYLLABLE KXWA
        {0x12C2, 0x12C5},        // ETHIOPIC SYLLABLE KXWI..ETHIOPIC SYLLABLE KXWE
        {0x12C8, 0x12D6},        // ETHIOPIC SYLLABLE WA..ETHIOPIC SYLLABLE PHARYNGEAL O
        {0x12D8, 0x1310},        // ETHIOPIC SYLLABLE ZA..ETHIOPIC SYLLABLE GWA
        {0x1312, 0x1315},        // ETHIOPIC SYLLABLE GWI..ETHIOPIC SYLLABLE GWE
        {0x1318, 0x135A},        // ETHIOPIC SYLLABLE GGA..ETHIOPIC SYLLABLE FYA
        {0x135F, 0x135F},        // ETHIOPIC COMBINING GEMINATION MARK
        {0x1369, 0x1371},        // ETHIOPIC DIGIT ONE..ETHIOPIC DIGIT NINE
        {0x1380, 0x138F},        // ETHIOPIC SYLLABLE SEBATBEIT MWA..ETHIOPIC SYLLABLE PWE
        {0x13A0, 0x13F4},        // CHEROKEE LETTER A..CHEROKEE LETTER YV
        {0x1401, 0x166C},        // CANADIAN SYLLABICS E..CANADIAN SYLLABICS CARRIER TTSA
        {0x166F, 0x1676},        // CANADIAN SYLLABICS QAI..CANADIAN SYLLABICS NNGAA
        {0x1681, 0x169A},        // OGHAM LETTER BEITH..OGHAM LETTER PEITH
        {0x16A0, 0x16EA},        // RUNIC LETTER FEHU FEOH FE F..RUNIC LETTER X
        {0x16EE, 0x16F0},        // RUNIC ARLAUG SYMBOL..RUNIC BELGTHOR SYMBOL
        {0x1700, 0x170C},        // TAGALOG LETTER A..TAGALOG LETTER YA
        {0x170E, 0x1711},        // TAGALOG LETTER LA..TAGALOG LETTER HA
        {0x1712, 0x1714},        // TAGALOG VOWEL SIGN I..TAGALOG SIGN VIRAMA
        {0x1720, 0x1731},        // HANUNOO LETTER A..HANUNOO LETTER HA
        {0x1732, 0x1734},        // HANUNOO VOWEL SIGN I..HANUNOO SIGN PAMUDPOD
        {0x1740, 0x1751},        // BUHID LETTER A..BUHID LETTER HA
        {0x1752, 0x1753},        // BUHID VOWEL SIGN I..BUHID VOWEL SIGN U
        {0x1760, 0x176C},        // TAGBANWA LETTER A..TAGBANWA LETTER YA
        {0x176E, 0x1770},        // TAGBANWA LETTER LA..TAGBANWA LETTER SA
        {0x1772, 0x1773},        // TAGBANWA VOWEL SIGN I..TAGBANWA VOWEL SIGN U
        {0x1780, 0x17B3},        // KHMER LETTER KA..KHMER INDEPENDENT VOWEL QAU
        {0x17B6, 0x17B6},        // KHMER VOWEL SIGN AA
        {0x17B7, 0x17BD},        // KHMER VOWEL SIGN I..KHMER VOWEL SIGN UA
        {0x17BE, 0x17C5},        // KHMER VOWEL SIGN OE..KHMER VOWEL SIGN AU
        {0x17C6, 0x17C6},        // KHMER SIGN NIKAHIT
        {0x17C7, 0x17C8},        // KHMER SIGN REAHMUK..KHMER SIGN YUUKALEAPINTU
        {0x17C9, 0x17D3},        // KHMER SIGN MUUSIKATOAN..KHMER SIGN BATHAMASAT
        {0x17D7, 0x17D7},        // KHMER SIGN LEK TOO
        {0x17DC, 0x17DC},        // KHMER SIGN AVAKRAHASANYA
        {0x17DD, 0x17DD},        // KHMER SIGN ATTHACAN
        {0x17E0, 0x17E9},        // KHMER DIGIT ZERO..KHMER DIGIT NINE
        {0x180B, 0x180D},        // MONGOLIAN FREE VARIATION SELECTOR ONE..MONGOLIAN FREE VARIATION SELECTOR THREE
        {0x1810, 0x1819},        // MONGOLIAN DIGIT ZERO..MONGOLIAN DIGIT NINE
        {0x1820, 0x1842},        // MONGOLIAN LETTER A..MONGOLIAN LETTER CHI
        {0x1843, 0x1843},        // MONGOLIAN LETTER TODO LONG VOWEL SIGN
        {0x1844, 0x1877},        // MONGOLIAN LETTER TODO E..MONGOLIAN LETTER MANCHU ZHA
        {0x1880, 0x18A8},        // MONGOLIAN LETTER ALI GALI ANUSVARA ONE..MONGOLIAN LETTER MANCHU ALI GALI BHA
        {0x18A9, 0x18A9},        // MONGOLIAN LETTER ALI GALI DAGALGA
        {0x1900, 0x191C},        // LIMBU VOWEL-CARRIER LETTER..LIMBU LETTER HA
        {0x1920, 0x1922},        // LIMBU VOWEL SIGN A..LIMBU VOWEL SIGN U
        {0x1923, 0x1926},        // LIMBU VOWEL SIGN EE..LIMBU VOWEL SIGN AU
        {0x1927, 0x1928},        // LIMBU VOWEL SIGN E..LIMBU VOWEL SIGN O
        {0x1929, 0x192B},        // LIMBU SUBJOINED LETTER YA..LIMBU SUBJOINED LETTER WA
        {0x1930, 0x1931},        // LIMBU SMALL LETTER KA..LIMBU SMALL LETTER NGA
        {0x1932, 0x1932},        // LIMBU SMALL LETTER ANUSVARA
        {0x1933, 0x1938},        // LIMBU SMALL LETTER TA..LIMBU SMALL LETTER LA
        {0x1939, 0x193B},        // LIMBU SIGN MUKPHRENG..LIMBU SIGN SA-I
        {0x1946, 0x194F},        // LIMBU DIGIT ZERO..LIMBU DIGIT NINE
        {0x1950, 0x196D},        // TAI LE LETTER KA..TAI LE LETTER AI
        {0x1970, 0x1974},        // TAI LE LETTER TONE-2..TAI LE LETTER TONE-6
        {0x1980, 0x19A9},        // NEW TAI LUE LETTER HIGH QA..NEW TAI LUE LETTER LOW XVA
        {0x19B0, 0x19C0},        // NEW TAI LUE VOWEL SIGN VOWEL SHORTENER..NEW TAI LUE VOWEL SIGN IY
        {0x19C1, 0x19C7},        // NEW TAI LUE LETTER FINAL V..NEW TAI LUE LETTER FINAL B
        {0x19C8, 0x19C9},        // NEW TAI LUE TONE MARK-1..NEW TAI LUE TONE MARK-2
        {0x19D0, 0x19D9},        // NEW TAI LUE DIGIT ZERO..NEW TAI LUE DIGIT NINE
        {0x1A00, 0x1A16},        // BUGINESE LETTER KA..BUGINESE LETTER HA
        {0x1A17, 0x1A18},        // BUGINESE VOWEL SIGN I..BUGINESE VOWEL SIGN U
        {0x1A19, 0x1A1B},        // BUGINESE VOWEL SIGN E..BUGINESE VOWEL SIGN AE
        {0x1B00, 0x1B03},        // BALINESE SIGN ULU RICEM..BALINESE SIGN SURANG
        {0x1B04, 0x1B04},        // BALINESE SIGN BISAH
        {0x1B05, 0x1B33},        // BALINESE LETTER AKARA..BALINESE LETTER HA
        {0x1B34, 0x1B34},        // BALINESE SIGN REREKAN
        {0x1B35, 0x1B35},        // BALINESE VOWEL SIGN TEDUNG
        {0x1B36, 0x1B3A},        // BALINESE VOWEL SIGN ULU..BALINESE VOWEL SIGN RA REPA
        {0x1B3B, 0x1B3B},        // BALINESE VOWEL SIGN RA REPA TEDUNG
        {0x1B3C, 0x1B3C},        // BALINESE VOWEL SIGN LA LENGA
        {0x1B3D, 0x1B41},        // BALINESE VOWEL SIGN LA LENGA TEDUNG..BALINESE VOWEL SIGN TALING REPA TEDUNG
        {0x1B42, 0x1B42},        // BALINESE VOWEL SIGN PEPET
        {0x1B43, 0x1B44},        // BALINESE VOWEL SIGN PEPET TEDUNG..BALINESE ADEG ADEG
        {0x1B45, 0x1B4B},        // BALINESE LETTER KAF SASAK..BALINESE LETTER ASYURA SASAK
        {0x1B50, 0x1B59},        // BALINESE DIGIT ZERO..BALINESE DIGIT NINE
        {0x1B6B, 0x1B73},        // BALINESE MUSICAL SYMBOL COMBINING TEGEH..BALINESE MUSICAL SYMBOL COMBINING GONG
        {0x1D00, 0x1D2B},        // LATIN LETTER SMALL CAPITAL A..CYRILLIC LETTER SMALL CAPITAL EL
        {0x1D2C, 0x1D61},        // MODIFIER LETTER CAPITAL A..MODIFIER LETTER SMALL CHI
        {0x1D62, 0x1D77},        // LATIN SUBSCRIPT SMALL LETTER I..LATIN SMALL LETTER TURNED G
        {0x1D78, 0x1D78},        // MODIFIER LETTER CYRILLIC EN
        {0x1D79, 0x1D9A},        // LATIN SMALL LETTER INSULAR G..LATIN SMALL LETTER EZH WITH RETROFLEX HOOK
        {0x1D9B, 0x1DBF},        // MODIFIER LETTER SMALL TURNED ALPHA..MODIFIER LETTER SMALL THETA
        {0x1DC0, 0x1DCA},        // COMBINING DOTTED GRAVE ACCENT..COMBINING LATIN SMALL LETTER R BELOW
        {0x1DFE, 0x1DFF},        // COMBINING LEFT ARROWHEAD ABOVE..COMBINING RIGHT ARROWHEAD AND DOWN ARROWHEAD BELOW
        {0x1E00, 0x1E9B},        // LATIN CAPITAL LETTER A WITH RING BELOW..LATIN SMALL LETTER LONG S WITH DOT ABOVE
        {0x1EA0, 0x1EF9},        // LATIN CAPITAL LETTER A WITH DOT BELOW..LATIN SMALL LETTER Y WITH TILDE
        {0x1F00, 0x1F15},        // GREEK SMALL LETTER ALPHA WITH PSILI..GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
        {0x1F18, 0x1F1D},        // GREEK CAPITAL LETTER EPSILON WITH PSILI..GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
        {0x1F20, 0x1F45},        // GREEK SMALL LETTER ETA WITH PSILI..GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
        {0x1F48, 0x1F4D},        // GREEK CAPITAL LETTER OMICRON WITH PSILI..GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
        {0x1F50, 0x1F57},        // GREEK SMALL LETTER UPSILON WITH PSILI..GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
        {0x1F59, 0x1F59},        // GREEK CAPITAL LETTER UPSILON WITH DASIA
        {0x1F5B, 0x1F5B},        // GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
        {0x1F5D, 0x1F5D},        // GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
        {0x1F5F, 0x1F7D},        // GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI..GREEK SMALL LETTER OMEGA WITH OXIA
        {0x1F80, 0x1FB4},        // GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI..GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
        {0x1FB6, 0x1FBC},        // GREEK SMALL LETTER ALPHA WITH PERISPOMENI..GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
        {0x1FBE, 0x1FBE},        // GREEK PROSGEGRAMMENI
        {0x1FC2, 0x1FC4},        // GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI..GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
        {0x1FC6, 0x1FCC},        // GREEK SMALL LETTER ETA WITH PERISPOMENI..GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
        {0x1FD0, 0x1FD3},        // GREEK SMALL LETTER IOTA WITH VRACHY..GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
        {0x1FD6, 0x1FDB},        // GREEK SMALL LETTER IOTA WITH PERISPOMENI..GREEK CAPITAL LETTER IOTA WITH OXIA
        {0x1FE0, 0x1FEC},        // GREEK SMALL LETTER UPSILON WITH VRACHY..GREEK CAPITAL LETTER RHO WITH DASIA
        {0x1FF2, 0x1FF4},        // GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI..GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
        {0x1FF6, 0x1FFC},        // GREEK SMALL LETTER OMEGA WITH PERISPOMENI..GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
        {0x203F, 0x2040},        // UNDERTIE..CHARACTER TIE
        {0x2054, 0x2054},        // INVERTED UNDERTIE
        {0x2071, 0x2071},        // SUPERSCRIPT LATIN SMALL LETTER I
        {0x207F, 0x207F},        // SUPERSCRIPT LATIN SMALL LETTER N
        {0x2090, 0x2094},        // LATIN SUBSCRIPT SMALL LETTER A..LATIN SUBSCRIPT SMALL LETTER SCHWA
        {0x20D0, 0x20DC},        // COMBINING LEFT HARPOON ABOVE..COMBINING FOUR DOTS ABOVE
        {0x20E1, 0x20E1},        // COMBINING LEFT RIGHT ARROW ABOVE
        {0x20E5, 0x20EF},        // COMBINING REVERSE SOLIDUS OVERLAY..COMBINING RIGHT ARROW BELOW
        {0x2102, 0x2102},        // DOUBLE-STRUCK CAPITAL C
        {0x2107, 0x2107},        // EULER CONSTANT
        {0x210A, 0x2113},        // SCRIPT SMALL G..SCRIPT SMALL L
        {0x2115, 0x2115},        // DOUBLE-STRUCK CAPITAL N
        {0x2118, 0x2118},        // SCRIPT CAPITAL P
        {0x2119, 0x211D},        // DOUBLE-STRUCK CAPITAL P..DOUBLE-STRUCK CAPITAL R
        {0x2124, 0x2124},        // DOUBLE-STRUCK CAPITAL Z
        {0x2126, 0x2126},        // OHM SIGN
        {0x2128, 0x2128},        // BLACK-LETTER CAPITAL Z
        {0x212A, 0x212D},        // KELVIN SIGN..BLACK-LETTER CAPITAL C
        {0x212E, 0x212E},        // ESTIMATED SYMBOL
        {0x212F, 0x2134},        // SCRIPT SMALL E..SCRIPT SMALL O
        {0x2135, 0x2138},        // ALEF SYMBOL..DALET SYMBOL
        {0x2139, 0x2139},        // INFORMATION SOURCE
        {0x213C, 0x213F},        // DOUBLE-STRUCK SMALL PI..DOUBLE-STRUCK CAPITAL PI
        {0x2145, 0x2149},        // DOUBLE-STRUCK ITALIC CAPITAL D..DOUBLE-STRUCK ITALIC SMALL J
        {0x214E, 0x214E},        // TURNED SMALL F
        {0x2160, 0x2182},        // ROMAN NUMERAL ONE..ROMAN NUMERAL TEN THOUSAND
        {0x2183, 0x2184},        // ROMAN NUMERAL REVERSED ONE HUNDRED..LATIN SMALL LETTER REVERSED C
        {0x2C00, 0x2C2E},        // GLAGOLITIC CAPITAL LETTER AZU..GLAGOLITIC CAPITAL LETTER LATINATE MYSLITE
        {0x2C30, 0x2C5E},        // GLAGOLITIC SMALL LETTER AZU..GLAGOLITIC SMALL LETTER LATINATE MYSLITE
        {0x2C60, 0x2C6C},        // LATIN CAPITAL LETTER L WITH DOUBLE BAR..LATIN SMALL LETTER Z WITH DESCENDER
        {0x2C74, 0x2C77},        // LATIN SMALL LETTER V WITH CURL..LATIN SMALL LETTER TAILLESS PHI
        {0x2C80, 0x2CE4},        // COPTIC CAPITAL LETTER ALFA..COPTIC SYMBOL KAI
        {0x2D00, 0x2D25},        // GEORGIAN SMALL LETTER AN..GEORGIAN SMALL LETTER HOE
        {0x2D30, 0x2D65},        // TIFINAGH LETTER YA..TIFINAGH LETTER YAZZ
        {0x2D6F, 0x2D6F},        // TIFINAGH MODIFIER LETTER LABIALIZATION MARK
        {0x2D80, 0x2D96},        // ETHIOPIC SYLLABLE LOA..ETHIOPIC SYLLABLE GGWE
        {0x2DA0, 0x2DA6},        // ETHIOPIC SYLLABLE SSA..ETHIOPIC SYLLABLE SSO
        {0x2DA8, 0x2DAE},        // ETHIOPIC SYLLABLE CCA..ETHIOPIC SYLLABLE CCO
        {0x2DB0, 0x2DB6},        // ETHIOPIC SYLLABLE ZZA..ETHIOPIC SYLLABLE ZZO
        {0x2DB8, 0x2DBE},        // ETHIOPIC SYLLABLE CCHA..ETHIOPIC SYLLABLE CCHO
        {0x2DC0, 0x2DC6},        // ETHIOPIC SYLLABLE QYA..ETHIOPIC SYLLABLE QYO
        {0x2DC8, 0x2DCE},        // ETHIOPIC SYLLABLE KYA..ETHIOPIC SYLLABLE KYO
        {0x2DD0, 0x2DD6},        // ETHIOPIC SYLLABLE XYA..ETHIOPIC SYLLABLE XYO
        {0x2DD8, 0x2DDE},        // ETHIOPIC SYLLABLE GYA..ETHIOPIC SYLLABLE GYO
        {0x3005, 0x3005},        // IDEOGRAPHIC ITERATION MARK
        {0x3006, 0x3006},        // IDEOGRAPHIC CLOSING MARK
        {0x3007, 0x3007},        // IDEOGRAPHIC NUMBER ZERO
        {0x3021, 0x3029},        // HANGZHOU NUMERAL ONE..HANGZHOU NUMERAL NINE
        {0x302A, 0x302F},        // IDEOGRAPHIC LEVEL TONE MARK..HANGUL DOUBLE DOT TONE MARK
        {0x3031, 0x3035},        // VERTICAL KANA REPEAT MARK..VERTICAL KANA REPEAT MARK LOWER HALF
        {0x3038, 0x303A},        // HANGZHOU NUMERAL TEN..HANGZHOU NUMERAL THIRTY
        {0x303B, 0x303B},        // VERTICAL IDEOGRAPHIC ITERATION MARK
        {0x303C, 0x303C},        // MASU MARK
        {0x3041, 0x3096},        // HIRAGANA LETTER SMALL A..HIRAGANA LETTER SMALL KE
        {0x3099, 0x309A},        // COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
        {0x309D, 0x309E},        // HIRAGANA ITERATION MARK..HIRAGANA VOICED ITERATION MARK
        {0x309F, 0x309F},        // HIRAGANA DIGRAPH YORI
        {0x30A1, 0x30FA},        // KATAKANA LETTER SMALL A..KATAKANA LETTER VO
        {0x30FC, 0x30FE},        // KATAKANA-HIRAGANA PROLONGED SOUND MARK..KATAKANA VOICED ITERATION MARK
        {0x30FF, 0x30FF},        // KATAKANA DIGRAPH KOTO
        {0x3105, 0x312C},        // BOPOMOFO LETTER B..BOPOMOFO LETTER GN
        {0x3131, 0x318E},        // HANGUL LETTER KIYEOK..HANGUL LETTER ARAEAE
        {0x31A0, 0x31B7},        // BOPOMOFO LETTER BU..BOPOMOFO FINAL LETTER H
        {0x31F0, 0x31FF},        // KATAKANA LETTER SMALL KU..KATAKANA LETTER SMALL RO
        {0x3400, 0x4DB5},        // CJK UNIFIED IDEOGRAPH-3400..CJK UNIFIED IDEOGRAPH-4DB5
        {0x4E00, 0x9FBB},        // CJK UNIFIED IDEOGRAPH-4E00..CJK UNIFIED IDEOGRAPH-9FBB
        {0xA000, 0xA014},        // YI SYLLABLE IT..YI SYLLABLE E
        {0xA015, 0xA015},        // YI SYLLABLE WU
        {0xA016, 0xA48C},        // YI SYLLABLE BIT..YI SYLLABLE YYR
        {0xA717, 0xA71A},        // MODIFIER LETTER DOT VERTICAL BAR..MODIFIER LETTER LOWER RIGHT CORNER ANGLE
        {0xA800, 0xA801},        // SYLOTI NAGRI LETTER A..SYLOTI NAGRI LETTER I
        {0xA802, 0xA802},        // SYLOTI NAGRI SIGN DVISVARA
        {0xA803, 0xA805},        // SYLOTI NAGRI LETTER U..SYLOTI NAGRI LETTER O
        {0xA806, 0xA806},        // SYLOTI NAGRI SIGN HASANTA
        {0xA807, 0xA80A},        // SYLOTI NAGRI LETTER KO..SYLOTI NAGRI LETTER GHO
        {0xA80B, 0xA80B},        // SYLOTI NAGRI SIGN ANUSVARA
        {0xA80C, 0xA822},        // SYLOTI NAGRI LETTER CO..SYLOTI NAGRI LETTER HO
        {0xA823, 0xA824},        // SYLOTI NAGRI VOWEL SIGN A..SYLOTI NAGRI VOWEL SIGN I
        {0xA825, 0xA826},        // SYLOTI NAGRI VOWEL SIGN U..SYLOTI NAGRI VOWEL SIGN E
        {0xA827, 0xA827},        // SYLOTI NAGRI VOWEL SIGN OO
        {0xA840, 0xA873},        // PHAGS-PA LETTER KA..PHAGS-PA LETTER CANDRABINDU
        {0xAC00, 0xD7A3},        // HANGUL SYLLABLE GA..HANGUL SYLLABLE HIH
        {0xF900, 0xFA2D},        // CJK COMPATIBILITY IDEOGRAPH-F900..CJK COMPATIBILITY IDEOGRAPH-FA2D
        {0xFA30, 0xFA6A},        // CJK COMPATIBILITY IDEOGRAPH-FA30..CJK COMPATIBILITY IDEOGRAPH-FA6A
        {0xFA70, 0xFAD9},        // CJK COMPATIBILITY IDEOGRAPH-FA70..CJK COMPATIBILITY IDEOGRAPH-FAD9
        {0xFB00, 0xFB06},        // LATIN SMALL LIGATURE FF..LATIN SMALL LIGATURE ST
        {0xFB13, 0xFB17},        // ARMENIAN SMALL LIGATURE MEN NOW..ARMENIAN SMALL LIGATURE MEN XEH
        {0xFB1D, 0xFB1D},        // HEBREW LETTER YOD WITH HIRIQ
        {0xFB1E, 0xFB1E},        // HEBREW POINT JUDEO-SPANISH VARIKA
        {0xFB1F, 0xFB28},        // HEBREW LIGATURE YIDDISH YOD YOD PATAH..HEBREW LETTER WIDE TAV
        {0xFB2A, 0xFB36},        // HEBREW LETTER SHIN WITH SHIN DOT..HEBREW LETTER ZAYIN WITH DAGESH
        {0xFB38, 0xFB3C},        // HEBREW LETTER TET WITH DAGESH..HEBREW LETTER LAMED WITH DAGESH
        {0xFB3E, 0xFB3E},        // HEBREW LETTER MEM WITH DAGESH
        {0xFB40, 0xFB41},        // HEBREW LETTER NUN WITH DAGESH..HEBREW LETTER SAMEKH WITH DAGESH
        {0xFB43, 0xFB44},        // HEBREW LETTER FINAL PE WITH DAGESH..HEBREW LETTER PE WITH DAGESH
        {0xFB46, 0xFBB1},        // HEBREW LETTER TSADI WITH DAGESH..ARABIC LETTER YEH BARREE WITH HAMZA ABOVE FINAL FORM
        {0xFBD3, 0xFC5D},        // ARABIC LETTER NG ISOLATED FORM..ARABIC LIGATURE ALEF MAKSURA WITH SUPERSCRIPT ALEF ISOLATED FORM
        {0xFC64, 0xFD3D},        // ARABIC LIGATURE YEH WITH HAMZA ABOVE WITH REH FINAL FORM..ARABIC LIGATURE ALEF WITH FATHATAN ISOLATED FORM
        {0xFD50, 0xFD8F},        // ARABIC LIGATURE TEH WITH JEEM WITH MEEM INITIAL FORM..ARABIC LIGATURE MEEM WITH KHAH WITH MEEM INITIAL FORM
        {0xFD92, 0xFDC7},        // ARABIC LIGATURE MEEM WITH JEEM WITH KHAH INITIAL FORM..ARABIC LIGATURE NOON WITH JEEM WITH YEH FINAL FORM
        {0xFDF0, 0xFDF9},        // ARABIC LIGATURE SALLA USED AS KORANIC STOP SIGN ISOLATED FORM..ARABIC LIGATURE SALLA ISOLATED FORM
        {0xFE00, 0xFE0F},        // VARIATION SELECTOR-1..VARIATION SELECTOR-16
        {0xFE20, 0xFE23},        // COMBINING LIGATURE LEFT HALF..COMBINING DOUBLE TILDE RIGHT HALF
        {0xFE33, 0xFE34},        // PRESENTATION FORM FOR VERTICAL LOW LINE..PRESENTATION FORM FOR VERTICAL WAVY LOW LINE
        {0xFE4D, 0xFE4F},        // DASHED LOW LINE..WAVY LOW LINE
        {0xFE71, 0xFE71},        // ARABIC TATWEEL WITH FATHATAN ABOVE
        {0xFE73, 0xFE73},        // ARABIC TAIL FRAGMENT
        {0xFE77, 0xFE77},        // ARABIC FATHA MEDIAL FORM
        {0xFE79, 0xFE79},        // ARABIC DAMMA MEDIAL FORM
        {0xFE7B, 0xFE7B},        // ARABIC KASRA MEDIAL FORM
        {0xFE7D, 0xFE7D},        // ARABIC SHADDA MEDIAL FORM
        {0xFE7F, 0xFEFC},        // ARABIC SUKUN MEDIAL FORM..ARABIC LIGATURE LAM WITH ALEF FINAL FORM
        {0xFF10, 0xFF19},        // FULLWIDTH DIGIT ZERO..FULLWIDTH DIGIT NINE
        {0xFF21, 0xFF3A},        // FULLWIDTH LATIN CAPITAL LETTER A..FULLWIDTH LATIN CAPITAL LETTER Z
        {0xFF3F, 0xFF3F},        // FULLWIDTH LOW LINE
        {0xFF41, 0xFF5A},        // FULLWIDTH LATIN SMALL LETTER A..FULLWIDTH LATIN SMALL LETTER Z
        {0xFF66, 0xFF6F},        // HALFWIDTH KATAKANA LETTER WO..HALFWIDTH KATAKANA LETTER SMALL TU
        {0xFF70, 0xFF70},        // HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
        {0xFF71, 0xFF9D},        // HALFWIDTH KATAKANA LETTER A..HALFWIDTH KATAKANA LETTER N
        {0xFF9E, 0xFF9F},        // HALFWIDTH KATAKANA VOICED SOUND MARK..HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
        {0xFFA0, 0xFFBE},        // HALFWIDTH HANGUL FILLER..HALFWIDTH HANGUL LETTER HIEUH
        {0xFFC2, 0xFFC7},        // HALFWIDTH HANGUL LETTER A..HALFWIDTH HANGUL LETTER E
        {0xFFCA, 0xFFCF},        // HALFWIDTH HANGUL LETTER YEO..HALFWIDTH HANGUL LETTER OE
        {0xFFD2, 0xFFD7},        // HALFWIDTH HANGUL LETTER YO..HALFWIDTH HANGUL LETTER YU
        {0xFFDA, 0xFFDC},        // HALFWIDTH HANGUL LETTER EU..HALFWIDTH HANGUL LETTER I
        {0x10000, 0x1000B},        // LINEAR B SYLLABLE B008 A..LINEAR B SYLLABLE B046 JE
        {0x1000D, 0x10026},        // LINEAR B SYLLABLE B036 JO..LINEAR B SYLLABLE B032 QO
        {0x10028, 0x1003A},        // LINEAR B SYLLABLE B060 RA..LINEAR B SYLLABLE B042 WO
        {0x1003C, 0x1003D},        // LINEAR B SYLLABLE B017 ZA..LINEAR B SYLLABLE B074 ZE
        {0x1003F, 0x1004D},        // LINEAR B SYLLABLE B020 ZO..LINEAR B SYLLABLE B091 TWO
        {0x10050, 0x1005D},        // LINEAR B SYMBOL B018..LINEAR B SYMBOL B089
        {0x10080, 0x100FA},        // LINEAR B IDEOGRAM B100 MAN..LINEAR B IDEOGRAM VESSEL B305
        {0x10140, 0x10174},        // GREEK ACROPHONIC ATTIC ONE QUARTER..GREEK ACROPHONIC STRATIAN FIFTY MNAS
        {0x10300, 0x1031E},        // OLD ITALIC LETTER A..OLD ITALIC LETTER UU
        {0x10330, 0x10340},        // GOTHIC LETTER AHSA..GOTHIC LETTER PAIRTHRA
        {0x10341, 0x10341},        // GOTHIC LETTER NINETY
        {0x10342, 0x10349},        // GOTHIC LETTER RAIDA..GOTHIC LETTER OTHAL
        {0x1034A, 0x1034A},        // GOTHIC LETTER NINE HUNDRED
        {0x10380, 0x1039D},        // UGARITIC LETTER ALPA..UGARITIC LETTER SSU
        {0x103A0, 0x103C3},        // OLD PERSIAN SIGN A..OLD PERSIAN SIGN HA
        {0x103C8, 0x103CF},        // OLD PERSIAN SIGN AURAMAZDAA..OLD PERSIAN SIGN BUUMISH
        {0x103D1, 0x103D5},        // OLD PERSIAN NUMBER ONE..OLD PERSIAN NUMBER HUNDRED
        {0x10400, 0x1044F},        // DESERET CAPITAL LETTER LONG I..DESERET SMALL LETTER EW
        {0x10450, 0x1049D},        // SHAVIAN LETTER PEEP..OSMANYA LETTER OO
        {0x104A0, 0x104A9},        // OSMANYA DIGIT ZERO..OSMANYA DIGIT NINE
        {0x10800, 0x10805},        // CYPRIOT SYLLABLE A..CYPRIOT SYLLABLE JA
        {0x10808, 0x10808},        // CYPRIOT SYLLABLE JO
        {0x1080A, 0x10835},        // CYPRIOT SYLLABLE KA..CYPRIOT SYLLABLE WO
        {0x10837, 0x10838},        // CYPRIOT SYLLABLE XA..CYPRIOT SYLLABLE XE
        {0x1083C, 0x1083C},        // CYPRIOT SYLLABLE ZA
        {0x1083F, 0x1083F},        // CYPRIOT SYLLABLE ZO
        {0x10900, 0x10915},        // PHOENICIAN LETTER ALF..PHOENICIAN LETTER TAU
        {0x10A00, 0x10A00},        // KHAROSHTHI LETTER A
        {0x10A01, 0x10A03},        // KHAROSHTHI VOWEL SIGN I..KHAROSHTHI VOWEL SIGN VOCALIC R
        {0x10A05, 0x10A06},        // KHAROSHTHI VOWEL SIGN E..KHAROSHTHI VOWEL SIGN O
        {0x10A0C, 0x10A0F},        // KHAROSHTHI VOWEL LENGTH MARK..KHAROSHTHI SIGN VISARGA
        {0x10A10, 0x10A13},        // KHAROSHTHI LETTER KA..KHAROSHTHI LETTER GHA
        {0x10A15, 0x10A17},        // KHAROSHTHI LETTER CA..KHAROSHTHI LETTER JA
        {0x10A19, 0x10A33},        // KHAROSHTHI LETTER NYA..KHAROSHTHI LETTER TTTHA
        {0x10A38, 0x10A3A},        // KHAROSHTHI SIGN BAR ABOVE..KHAROSHTHI SIGN DOT BELOW
        {0x10A3F, 0x10A3F},        // KHAROSHTHI VIRAMA
        {0x12000, 0x1236E},        // CUNEIFORM SIGN A..CUNEIFORM SIGN ZUM
        {0x12400, 0x12462},        // CUNEIFORM NUMERIC SIGN TWO ASH..CUNEIFORM NUMERIC SIGN OLD ASSYRIAN ONE QUARTER
        {0x1D165, 0x1D166},        // MUSICAL SYMBOL COMBINING STEM..MUSICAL SYMBOL COMBINING SPRECHGESANG STEM
        {0x1D167, 0x1D169},        // MUSICAL SYMBOL COMBINING TREMOLO-1..MUSICAL SYMBOL COMBINING TREMOLO-3
        {0x1D16D, 0x1D172},        // MUSICAL SYMBOL COMBINING AUGMENTATION DOT..MUSICAL SYMBOL COMBINING FLAG-5
        {0x1D17B, 0x1D182},        // MUSICAL SYMBOL COMBINING ACCENT..MUSICAL SYMBOL COMBINING LOURE
        {0x1D185, 0x1D18B},        // MUSICAL SYMBOL COMBINING DOIT..MUSICAL SYMBOL COMBINING TRIPLE TONGUE
        {0x1D1AA, 0x1D1AD},        // MUSICAL SYMBOL COMBINING DOWN BOW..MUSICAL SYMBOL COMBINING SNAP PIZZICATO
        {0x1D242, 0x1D244},        // COMBINING GREEK MUSICAL TRISEME..COMBINING GREEK MUSICAL PENTASEME
        {0x1D400, 0x1D454},        // MATHEMATICAL BOLD CAPITAL A..MATHEMATICAL ITALIC SMALL G
        {0x1D456, 0x1D49C},        // MATHEMATICAL ITALIC SMALL I..MATHEMATICAL SCRIPT CAPITAL A
        {0x1D49E, 0x1D49F},        // MATHEMATICAL SCRIPT CAPITAL C..MATHEMATICAL SCRIPT CAPITAL D
        {0x1D4A2, 0x1D4A2},        // MATHEMATICAL SCRIPT CAPITAL G
        {0x1D4A5, 0x1D4A6},        // MATHEMATICAL SCRIPT CAPITAL J..MATHEMATICAL SCRIPT CAPITAL K
        {0x1D4A9, 0x1D4AC},        // MATHEMATICAL SCRIPT CAPITAL N..MATHEMATICAL SCRIPT CAPITAL Q
        {0x1D4AE, 0x1D4B9},        // MATHEMATICAL SCRIPT CAPITAL S..MATHEMATICAL SCRIPT SMALL D
        {0x1D4BB, 0x1D4BB},        // MATHEMATICAL SCRIPT SMALL F
        {0x1D4BD, 0x1D4C3},        // MATHEMATICAL SCRIPT SMALL H..MATHEMATICAL SCRIPT SMALL N
        {0x1D4C5, 0x1D505},        // MATHEMATICAL SCRIPT SMALL P..MATHEMATICAL FRAKTUR CAPITAL B
        {0x1D507, 0x1D50A},        // MATHEMATICAL FRAKTUR CAPITAL D..MATHEMATICAL FRAKTUR CAPITAL G
        {0x1D50D, 0x1D514},        // MATHEMATICAL FRAKTUR CAPITAL J..MATHEMATICAL FRAKTUR CAPITAL Q
        {0x1D516, 0x1D51C},        // MATHEMATICAL FRAKTUR CAPITAL S..MATHEMATICAL FRAKTUR CAPITAL Y
        {0x1D51E, 0x1D539},        // MATHEMATICAL FRAKTUR SMALL A..MATHEMATICAL DOUBLE-STRUCK CAPITAL B
        {0x1D53B, 0x1D53E},        // MATHEMATICAL DOUBLE-STRUCK CAPITAL D..MATHEMATICAL DOUBLE-STRUCK CAPITAL G
        {0x1D540, 0x1D544},        // MATHEMATICAL DOUBLE-STRUCK CAPITAL I..MATHEMATICAL DOUBLE-STRUCK CAPITAL M
        {0x1D546, 0x1D546},        // MATHEMATICAL DOUBLE-STRUCK CAPITAL O
        {0x1D54A, 0x1D550},        // MATHEMATICAL DOUBLE-STRUCK CAPITAL S..MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
        {0x1D552, 0x1D6A5},        // MATHEMATICAL DOUBLE-STRUCK SMALL A..MATHEMATICAL ITALIC SMALL DOTLESS J
        {0x1D6A8, 0x1D6C0},        // MATHEMATICAL BOLD CAPITAL ALPHA..MATHEMATICAL BOLD CAPITAL OMEGA
        {0x1D6C2, 0x1D6DA},        // MATHEMATICAL BOLD SMALL ALPHA..MATHEMATICAL BOLD SMALL OMEGA
        {0x1D6DC, 0x1D6FA},        // MATHEMATICAL BOLD EPSILON SYMBOL..MATHEMATICAL ITALIC CAPITAL OMEGA
        {0x1D6FC, 0x1D714},        // MATHEMATICAL ITALIC SMALL ALPHA..MATHEMATICAL ITALIC SMALL OMEGA
        {0x1D716, 0x1D734},        // MATHEMATICAL ITALIC EPSILON SYMBOL..MATHEMATICAL BOLD ITALIC CAPITAL OMEGA
        {0x1D736, 0x1D74E},        // MATHEMATICAL BOLD ITALIC SMALL ALPHA..MATHEMATICAL BOLD ITALIC SMALL OMEGA
        {0x1D750, 0x1D76E},        // MATHEMATICAL BOLD ITALIC EPSILON SYMBOL..MATHEMATICAL SANS-SERIF BOLD CAPITAL OMEGA
        {0x1D770, 0x1D788},        // MATHEMATICAL SANS-SERIF BOLD SMALL ALPHA..MATHEMATICAL SANS-SERIF BOLD SMALL OMEGA
        {0x1D78A, 0x1D7A8},        // MATHEMATICAL SANS-SERIF BOLD EPSILON SYMBOL..MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMEGA
        {0x1D7AA, 0x1D7C2},        // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ALPHA..MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMEGA
        {0x1D7C4, 0x1D7CB},        // MATHEMATICAL SANS-SERIF BOLD ITALIC EPSILON SYMBOL..MATHEMATICAL BOLD SMALL DIGAMMA
        {0x1D7CE, 0x1D7FF},        // MATHEMATICAL BOLD DIGIT ZERO..MATHEMATICAL MONOSPACE DIGIT NINE
        {0x20000, 0x2A6D6},        // CJK UNIFIED IDEOGRAPH-20000..CJK UNIFIED IDEOGRAPH-2A6D6
        {0x2F800, 0x2FA1D},        // CJK COMPATIBILITY IDEOGRAPH-2F800..CJK COMPATIBILITY IDEOGRAPH-2FA1D
        {0xE0100, 0xE01EF},        // VARIATION SELECTOR-17..VARIATION SELECTOR-256
        {0, 0} // list terminator
    };
    static PropTable pattern( srcmap );
    return pattern.Lookup( ch );
}
